Repository Arize-ai/openinference, pull requests merged in 2024-10, with the labels that each got.

#1048 feat(core): add trace config
  js/.changeset/tame-poems-argue.md
  js/packages/openinference-core/jest.config.js
  js/packages/openinference-core/package.json
  js/packages/openinference-core/src/trace/index.ts
  js/packages/openinference-core/src/trace/trace-config/OISpan.ts
  js/packages/openinference-core/src/trace/trace-config/OITracer.ts
  js/packages/openinference-core/src/trace/trace-config/constants.ts
  js/packages/openinference-core/src/trace/trace-config/index.ts
  js/packages/openinference-core/src/trace/trace-config/maskingRules.ts
  js/packages/openinference-core/src/trace/trace-config/traceConfig.ts
  js/packages/openinference-core/src/trace/trace-config/types.ts
  js/packages/openinference-core/src/utils/typeUtils.ts
  js/packages/openinference-core/test/trace-config/OITracer.test.ts
  js/packages/openinference-core/test/trace-config/OpenInferenceSpan.test.ts
  js/packages/openinference-core/test/trace-config/maskingRules.test.ts
  js/packages/openinference-core/test/trace-config/traceConfig.test.ts
  js/packages/openinference-core/tsconfig.esm.json
  js/packages/openinference-core/tsconfig.esnext.json
  js/packages/openinference-core/tsconfig.json
  js/packages/openinference-instrumentation-openai/package.json
  js/pnpm-lock.yaml
Labels: size:XXL, lgtm

#990 feat(anthropic): streaming support
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_stream.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_utils.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_with_span.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_async_completions_streaming.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_async_messages_streaming.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_completions_streaming.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_messages_streaming.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_multiple_tool_calling_streaming.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:XXL, lgtm

#1055 fix(dspy): support dspy 2.5 and above
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_basic_qa.py
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_cohere.py
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_custom_lm.py
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_mistral.py
  python/instrumentation/openinference-instrumentation-dspy/examples/lm.py
  python/instrumentation/openinference-instrumentation-dspy/examples/lm/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/examples/lm/custom_lm.py
  python/instrumentation/openinference-instrumentation-dspy/examples/rag_module.py
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/TestLM.test_exception_event_recorded_on_lm_error.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/TestLM.test_openai_chat_completions_api_invoked_via_messages_kwarg.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/TestLM.test_openai_chat_completions_api_invoked_via_prompt_positional_argument.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/TestLM.test_openai_completions_api_invoked_via_prompt_positional_argument.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/TestLM.test_subclass.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_compilation.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_context_attributes_are_instrumented.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_rag_module.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XXL, lgtm

#1057 feat(dspy): add instrumentation for dspy adapters
  .gitignore
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:M, lgtm

#1058 fix(dspy): prevent the creation of duplicate span exception events
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_context_attributes_are_instrumented.yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:L, lgtm

#1053 fix: groq input messages
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_utils.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_with_span.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_wrappers.py
  python/instrumentation/openinference-instrumentation-groq/tests/test_instrumentor.py
Labels: size:L, lgtm

#1066 feat: fix groq readme
  python/instrumentation/openinference-instrumentation-groq/README.md
Labels: size:XS, lgtm

#1054 feat: Add `get_chain_root_span` utility for langchain instrumentation
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:L, lgtm

#1069 docs(openai): simplify tool calling example
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_function_calling.py
Labels: size:M, lgtm

#1071 feat(semcov): llm system and llm provicer conventions
  cspell.json
  js/.changeset/wild-maps-notice.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:L, lgtm

#1073 fix: gcp -> google
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:XS, lgtm

#1075 feat: Add system and provider attributes to openai spans
  js/.changeset/large-pears-vanish.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:L, lgtm

#1078 feat: add OITracer to autoinstrumentations providing support for attribute masking and context attribute inheritance
  js/.changeset/khaki-students-attend.md
  js/DEVELOPMENT.md
  js/packages/openinference-core/test/trace-config/OITracer.test.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentationUtils.ts
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/test/instrumentationUtils.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV1.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts
  js/packages/openinference-instrumentation-openai/jest.config.js
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/packages/openinference-vercel/README.md
Labels: size:XL, lgtm

#1083 docs(js): update vercel and langchain examples add readme for openinference-core
  js/examples/langchain-express/backend/Dockerfile
  js/examples/langchain-express/backend/package.json
  js/examples/langchain-express/backend/src/controllers/chat.controller.ts
  js/examples/langchain-express/backend/src/vector_store/store.ts
  js/examples/langchain-express/frontend/Dockerfile
  js/examples/langchain-express/frontend/package.json
  js/examples/next-openai-telemetry-app/README.md
  js/examples/next-openai-telemetry-app/instrumentation.ts
  js/examples/next-openai-telemetry-app/next.config.js
  js/examples/next-openai-telemetry-app/next.config.ts
  js/packages/openinference-core/README.md
  spec/configuration.md
Labels: size:L, lgtm

#1084 feat(anthropic): add llm provider and system attributes to anthropic instrumentation
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:M, lgtm

#1082 feat(openai): add llm provider and system attributes
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:L, lgtm

#1086 refactor(anthropic): create helper functions for wrangling attributes
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
Labels: size:L, lgtm

#1085 feat: add tool call id
  python/openinference-semantic-conventions/pyproject.toml
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_attributes.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_enums.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_version.py
  spec/semantic_conventions.md
Labels: size:L, lgtm

#1089 chore: use tox to add symlinks
  python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
  python/openinference-instrumentation/src/openinference/instrumentation/bedrock
  python/openinference-instrumentation/src/openinference/instrumentation/crewai
  python/openinference-instrumentation/src/openinference/instrumentation/dspy
  python/openinference-instrumentation/src/openinference/instrumentation/guardrails
  python/openinference-instrumentation/src/openinference/instrumentation/haystack
  python/openinference-instrumentation/src/openinference/instrumentation/langchain
  python/openinference-instrumentation/src/openinference/instrumentation/litellm
  python/openinference-instrumentation/src/openinference/instrumentation/llama_index
  python/openinference-instrumentation/src/openinference/instrumentation/mistralai
  python/openinference-instrumentation/src/openinference/instrumentation/openai
  python/openinference-instrumentation/src/openinference/instrumentation/vertexai
  python/tox.ini
Labels: size:S, lgtm

#1087 feat(anthropic): add tool json schema attributes to anthropic instrumentation
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:L, lgtm

#1090 feat: add tool call id to openai instrumentor
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/cassettes/test_tool_calls.yaml
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_tool_calls.py
Labels: size:L, lgtm

#1093 fix: remove httpx dependency
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/test-requirements.txt
  python/tox.ini
Labels: size:M, lgtm

#1096 ci: fix type check for vertexai tests
  python/instrumentation/openinference-instrumentation-vertexai/tests/test_gapic_client.py
Labels: size:XS, lgtm

#1094 fix: remove anthropic dependency
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/__init__.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_stream.py
  python/instrumentation/openinference-instrumentation-anthropic/test-requirements.txt
  python/tox.ini
Labels: size:M, lgtm
