Repository Arize-ai/openinference, pull requests merged in 2024-01, with the labels that each got.

#116 feat(js): openai tool and function call support on streaming
  js/.changeset/short-forks-speak.md
  js/.eslintrc.js
  js/examples/openai/src/index.ts
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/src/typeUtils.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
Labels: language: js, size:L, lgtm

#118 chore: add requirements.txt to examples
  python/instrumentation/openinference-instrumentation-openai/examples/requirements.txt
Labels: size:XS, lgtm

#120 fix(spec): correct the prompt template variables
  spec/semantic_conventions.md
Labels: size:XS

#122 chore: include tests for mypy
  python/mypy.ini
  python/openinference-semantic-conventions/tests/openinference/semconv/test_version.py
  python/tox.ini
Labels: size:S, lgtm

#123 refactor: clean up stream exception logic
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_stream.py
Labels: size:M, lgtm

#121 feat: llama-index instrumentor using callback handler
  README.md
  python/instrumentation/openinference-instrumentation-llama-index/LICENSE
  python/instrumentation/openinference-instrumentation-llama-index/README.rst
  python/instrumentation/openinference-instrumentation-llama-index/examples/chroma_query_engine.py
  python/instrumentation/openinference-instrumentation-llama-index/examples/data/paul_graham/paul_graham_essay.txt
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/package.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/py.typed
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/version.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
  python/tox.ini
Labels: size:XXL, lgtm

#129 chore: add llama-index instrumentor to release please
  release-please-config.json
Labels: size:XS, lgtm

#128 chore(js): create-llama express app example
  .gitignore
  js/examples/llama-index-express/README.md
  js/examples/llama-index-express/backend/.eslintrc.json
  js/examples/llama-index-express/backend/.gitignore
  js/examples/llama-index-express/backend/README.md
  js/examples/llama-index-express/backend/index.ts
  js/examples/llama-index-express/backend/instrumentation.ts
  js/examples/llama-index-express/backend/package-lock.json
  js/examples/llama-index-express/backend/package.json
  js/examples/llama-index-express/backend/src/controllers/chat.controller.ts
  js/examples/llama-index-express/backend/src/controllers/engine/index.ts
  js/examples/llama-index-express/backend/src/controllers/llamaindex-stream.ts
  js/examples/llama-index-express/backend/src/routes/chat.route.ts
  js/examples/llama-index-express/backend/tsconfig.json
  js/examples/llama-index-express/frontend/.env.example
  js/examples/llama-index-express/frontend/.eslintrc.json
  js/examples/llama-index-express/frontend/.gitignore
  js/examples/llama-index-express/frontend/README.md
  js/examples/llama-index-express/frontend/app/components/chat-section.tsx
  js/examples/llama-index-express/frontend/app/components/header.tsx
  js/examples/llama-index-express/frontend/app/components/transform.ts
  js/examples/llama-index-express/frontend/app/components/ui/chat/chat-avatar.tsx
  js/examples/llama-index-express/frontend/app/components/ui/chat/chat-input.tsx
  js/examples/llama-index-express/frontend/app/components/ui/chat/chat-item.tsx
  js/examples/llama-index-express/frontend/app/components/ui/chat/chat-messages.tsx
  js/examples/llama-index-express/frontend/app/components/ui/chat/index.ts
  js/examples/llama-index-express/frontend/app/favicon.ico
  js/examples/llama-index-express/frontend/app/globals.css
  js/examples/llama-index-express/frontend/app/layout.tsx
  js/examples/llama-index-express/frontend/app/page.tsx
  js/examples/llama-index-express/frontend/next.config.js
  js/examples/llama-index-express/frontend/package-lock.json
  js/examples/llama-index-express/frontend/package.json
  js/examples/llama-index-express/frontend/postcss.config.js
  js/examples/llama-index-express/frontend/public/llama.png
  js/examples/llama-index-express/frontend/tailwind.config.ts
  js/examples/llama-index-express/frontend/tsconfig.json
  js/examples/openai/package.json
  js/examples/openai/src/index.ts
  js/examples/openai/src/instrumentation.ts
  js/package.json
Labels: size:XL, lgtm

#131 chore: add docker compose.yml for llama-create express app
  js/examples/llama-index-express/backend/Dockerfile
  js/examples/llama-index-express/backend/instrumentation.ts
  js/examples/llama-index-express/compose.yml
  js/examples/llama-index-express/frontend/Dockerfile
  js/examples/llama-index-express/frontend/app/components/ui/chat/chat-messages.tsx
Labels: size:M

#132 chore: disable tox spinner
  .github/workflows/python-CI.yaml
Labels: size:XS, lgtm

#115 feat: Add boto3 instrumentation
  python/instrumentation/openinference-instrumentation-bedrock/LICENSE
  python/instrumentation/openinference-instrumentation-bedrock/README.rst
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_example.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/package.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/py.typed
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/version.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
  python/mypy.ini
  python/tox.ini
Labels: size:L, lgtm

#133 chore(js): set up productionized builds for docker compose
  js/examples/llama-index-express/README.md
  js/examples/llama-index-express/backend/Dockerfile
  js/examples/llama-index-express/compose.yml
  js/examples/llama-index-express/frontend/Dockerfile
  js/examples/llama-index-express/frontend/next.config.js
Labels: size:M, lgtm

#126 feat(python): dspy lm instrumentation
  .github/workflows/python-CI.yaml
  .gitignore
  cspell.json
  python/instrumentation/openinference-instrumentation-dspy/LICENSE
  python/instrumentation/openinference-instrumentation-dspy/README.rst
  python/instrumentation/openinference-instrumentation-dspy/examples/.gitignore
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_basic_qa.py
  python/instrumentation/openinference-instrumentation-dspy/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/package.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/version.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/py.typed
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
  python/mypy.ini
  python/tox.ini
  release-please-config.json
Labels: size:XL, lgtm

#137 docs: add dspy to README
  README.md
Labels: size:XS, lgtm

#142 chore: Update READMEs to include Bedrock instrumentor and add Bedrock to release-please
  README.md
  python/instrumentation/openinference-instrumentation-bedrock/README.rst
  release-please-config.json
Labels: size:S, lgtm

#127 docs(python): llama-index example
  python/examples/llama-index/README.md
  python/examples/llama-index/backend/.gitignore
  python/examples/llama-index/backend/Dockerfile
  python/examples/llama-index/backend/README.md
  python/examples/llama-index/backend/app/__init__.py
  python/examples/llama-index/backend/app/api/__init__.py
  python/examples/llama-index/backend/app/api/routers/__init__.py
  python/examples/llama-index/backend/app/api/routers/chat.py
  python/examples/llama-index/backend/app/context.py
  python/examples/llama-index/backend/app/engine/__init__.py
  python/examples/llama-index/backend/app/engine/constants.py
  python/examples/llama-index/backend/app/engine/context.py
  python/examples/llama-index/backend/app/engine/generate.py
  python/examples/llama-index/backend/app/engine/index.py
  python/examples/llama-index/backend/data/101.pdf
  python/examples/llama-index/backend/instrument.py
  python/examples/llama-index/backend/main.py
  python/examples/llama-index/backend/poetry.lock
  python/examples/llama-index/backend/pyproject.toml
  python/examples/llama-index/backend/tests/__init__.py
  python/examples/llama-index/compose.yml
  python/examples/llama-index/frontend/.env.example
  python/examples/llama-index/frontend/.gitignore
  python/examples/llama-index/frontend/Dockerfile
  python/examples/llama-index/frontend/README.md
  python/examples/llama-index/frontend/app/components/chat-section.tsx
  python/examples/llama-index/frontend/app/components/header.tsx
  python/examples/llama-index/frontend/app/components/transform.ts
  python/examples/llama-index/frontend/app/components/ui/chat/chat-avatar.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-input.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-item.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-messages.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/index.ts
  python/examples/llama-index/frontend/app/favicon.ico
  python/examples/llama-index/frontend/app/globals.css
  python/examples/llama-index/frontend/app/layout.tsx
  python/examples/llama-index/frontend/app/page.tsx
  python/examples/llama-index/frontend/next.config.js
  python/examples/llama-index/frontend/package-lock.json
  python/examples/llama-index/frontend/package.json
  python/examples/llama-index/frontend/postcss.config.js
  python/examples/llama-index/frontend/public/llama.png
  python/examples/llama-index/frontend/tailwind.config.ts
  python/examples/llama-index/frontend/tsconfig.json
Labels: size:XL, lgtm

#138 feat: langchain instrumentor
  README.md
  python/instrumentation/openinference-instrumentation-langchain/LICENSE
  python/instrumentation/openinference-instrumentation-langchain/README.rst
  python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
  python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/package.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/py.typed
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/version.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
  python/tox.ini
  release-please-config.json
Labels: size:XXL, lgtm

#152 fix: bedrock README.rst
  python/instrumentation/openinference-instrumentation-bedrock/README.rst
Labels: size:XS, lgtm

#151 fix: Build index during backend build step
  python/examples/llama-index/README.md
  python/examples/llama-index/backend/Dockerfile
  python/examples/llama-index/compose.yml
Labels: size:S, lgtm

#155 fix: enforce explicit parent context at span creation for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:S, lgtm

#159 docs: add example READMEs
  cspell.json
  js/examples/README.md
  python/examples/README.md
Labels: size:M

#160 docs: update example readmes
  js/examples/llama-index-express/README.md
  js/examples/openai/README.md
  python/examples/llama-index/README.md
Labels: size:S
