Repository Arize-ai/openinference, pull requests merged in 2024-04, with the labels that each got.

#351 chore: re-lock poetry for llama-index example
  python/examples/llama-index/backend/poetry.lock
Labels: size:XS, lgtm

#355 ci: add langchainjs ci rules
  .github/workflows/typescript-CI.yaml
Labels: size:XS, lgtm

#357 feat: scaffold langchainjs instrumentation package
  js/packages/openinference-instrumentation-langchain/README.md
  js/packages/openinference-instrumentation-langchain/jest.config.js
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/index.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/tsconfig.esm.json
  js/packages/openinference-instrumentation-langchain/tsconfig.esnext.json
  js/packages/openinference-instrumentation-langchain/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:M, lgtm

#353 fix: Enables `uninstrument` method on `LangchainInstrumentor`
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
Labels: size:XS, lgtm

#361 feat(js): support trace supression for openai
  cspell.json
  js/packages/openinference-core/src/trace/session.ts
  js/packages/openinference-instrumentation-openai/package.json
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/pnpm-lock.yaml
Labels: size:M, lgtm

#365 chore: bump node version in typescript-CI
  .github/workflows/typescript-CI.yaml
Labels: size:XS, lgtm

#364 feat(python): Migrate llama-index example to v0.10+
  python/examples/llama-index/README.md
  python/examples/llama-index/backend/README.md
  python/examples/llama-index/backend/app/api/routers/chat.py
  python/examples/llama-index/backend/app/context.py
  python/examples/llama-index/backend/app/engine/__init__.py
  python/examples/llama-index/backend/app/engine/constants.py
  python/examples/llama-index/backend/app/engine/context.py
  python/examples/llama-index/backend/app/engine/generate.py
  python/examples/llama-index/backend/app/engine/index.py
  python/examples/llama-index/backend/app/engine/loaders/__init__.py
  python/examples/llama-index/backend/app/engine/loaders/file.py
  python/examples/llama-index/backend/app/settings.py
  python/examples/llama-index/backend/config/loaders.yaml
  python/examples/llama-index/backend/main.py
  python/examples/llama-index/backend/poetry.lock
  python/examples/llama-index/backend/pyproject.toml
  python/examples/llama-index/frontend/.env.example
  python/examples/llama-index/frontend/.eslintrc.json
  python/examples/llama-index/frontend/app/components/ui/README.md
  python/examples/llama-index/frontend/app/components/ui/button.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-actions.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-avatar.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-input.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-item.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-message.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat-messages.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/chat.interface.ts
  python/examples/llama-index/frontend/app/components/ui/chat/codeblock.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/index.ts
  python/examples/llama-index/frontend/app/components/ui/chat/markdown.tsx
  python/examples/llama-index/frontend/app/components/ui/chat/use-copy-to-clipboard.tsx
  python/examples/llama-index/frontend/app/components/ui/file-uploader.tsx
  python/examples/llama-index/frontend/app/components/ui/input.tsx
  python/examples/llama-index/frontend/app/components/ui/lib/utils.ts
  python/examples/llama-index/frontend/app/components/ui/upload-image-preview.tsx
  python/examples/llama-index/frontend/app/layout.tsx
  python/examples/llama-index/frontend/app/markdown.css
  python/examples/llama-index/frontend/app/observability/index.ts
  python/examples/llama-index/frontend/next.config.js
  python/examples/llama-index/frontend/next.config.json
  python/examples/llama-index/frontend/next.config.mjs
  python/examples/llama-index/frontend/package-lock.json
  python/examples/llama-index/frontend/package.json
  python/examples/llama-index/frontend/prettier.config.js
  python/examples/llama-index/frontend/tsconfig.json
  python/examples/llama-index/frontend/webpack.config.mjs
Labels: size:XL, lgtm

#367 fix: fix formatting and types in langchain instrumentation
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
Labels: size:XS, lgtm

#362 feat(langchainjs): patch callbacks module add tracer and input / output support
  js/.eslintrc.js
  js/packages/openinference-instrumentation-langchain/examples/chat.ts
  js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/jest.config.js
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/index.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/src/typeUtils.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/fixtures.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
  js/packages/openinference-instrumentation-langchain/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XXL, lgtm

#369 fix: dependabot warnings
  python/examples/llama-index/backend/poetry.lock
  python/examples/llama-index/backend/pyproject.toml
  python/examples/llama-index/frontend/package-lock.json
  python/examples/llama-index/frontend/package.json
Labels: size:S, lgtm

#354 feat: add lanchain.js express example
  js/examples/langchain-express/README.md
  js/examples/langchain-express/backend/.eslintrc.json
  js/examples/langchain-express/backend/.gitignore
  js/examples/langchain-express/backend/Dockerfile
  js/examples/langchain-express/backend/README.md
  js/examples/langchain-express/backend/index.ts
  js/examples/langchain-express/backend/instrumentation.ts
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/backend/package.json
  js/examples/langchain-express/backend/src/controllers/chat.controller.ts
  js/examples/langchain-express/backend/src/routes/chat.route.ts
  js/examples/langchain-express/backend/tsconfig.json
  js/examples/langchain-express/compose.yml
  js/examples/langchain-express/frontend/.env.example
  js/examples/langchain-express/frontend/.eslintrc.json
  js/examples/langchain-express/frontend/.gitignore
  js/examples/langchain-express/frontend/Dockerfile
  js/examples/langchain-express/frontend/README.md
  js/examples/langchain-express/frontend/app/components/chat-section.tsx
  js/examples/langchain-express/frontend/app/components/header.tsx
  js/examples/langchain-express/frontend/app/components/transform.ts
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-avatar.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-input.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-item.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-messages.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/index.ts
  js/examples/langchain-express/frontend/app/favicon.ico
  js/examples/langchain-express/frontend/app/globals.css
  js/examples/langchain-express/frontend/app/layout.tsx
  js/examples/langchain-express/frontend/app/page.tsx
  js/examples/langchain-express/frontend/next.config.js
  js/examples/langchain-express/frontend/package-lock.json
  js/examples/langchain-express/frontend/package.json
  js/examples/langchain-express/frontend/postcss.config.js
  js/examples/langchain-express/frontend/public/arize_logo.png
  js/examples/langchain-express/frontend/tailwind.config.ts
  js/examples/langchain-express/frontend/tsconfig.json
Labels: size:XL, lgtm

#370 feat(langchainjs): add retrieval and invocation parameters support to tracer
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/fixtures.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
Labels: size:L, lgtm

#371 feat(langchainjs): support top level function and tool calling
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/constants.ts
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/src/typeUtils.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/fixtures.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
  js/pnpm-lock.yaml
Labels: size:XXL, lgtm

#374 docs: new llama-index example
  python/examples/llama-index/README.md
  python/examples/llama-index/backend/Dockerfile
  python/examples/llama-index/backend/README.md
  python/examples/llama-index/backend/app/api/routers/chat.py
  python/examples/llama-index/backend/app/engine/__init__.py
  python/examples/llama-index/backend/app/engine/generate.py
  python/examples/llama-index/backend/app/engine/index.py
  python/examples/llama-index/backend/app/engine/loaders/__init__.py
  python/examples/llama-index/backend/app/engine/loaders/db.py
  python/examples/llama-index/backend/app/engine/loaders/file.py
  python/examples/llama-index/backend/app/engine/loaders/web.py
  python/examples/llama-index/backend/app/settings.py
  python/examples/llama-index/backend/instrument.py
  python/examples/llama-index/backend/main.py
  python/examples/llama-index/backend/poetry.lock
  python/examples/llama-index/backend/pyproject.toml
  python/examples/llama-index/compose.yaml
  python/examples/llama-index/frontend/Dockerfile
  python/examples/llama-index/frontend/README.md
  python/examples/llama-index/frontend/next.config.json
  python/examples/llama-index/frontend/package-lock.json
  python/examples/llama-index/frontend/package.json
Labels: size:L, lgtm

#375 fix: Resolve networking when using `docker compose` setup of LlamaIndex example
  python/examples/llama-index/backend/app/settings.py
  python/examples/llama-index/frontend/Dockerfile
Labels: size:XS, lgtm

#376 docs: Update readme for current state of LlamaIndex example
  python/examples/llama-index/README.md
Labels: size:M, lgtm

#373 feat: add semantic conventions for prompt template, retrieval documents, tools, and functions
  js/.changeset/polite-candles-wash.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:M, lgtm

#380 chore: update deps, cleanup test setup
  js/packages/openinference-instrumentation-langchain/examples/chat.ts
  js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/jest.config.js
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/constants.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/fixtures.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
  js/packages/openinference-instrumentation-langchain/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:L, lgtm

#378 feat(langchain): add LangChain.js instrumentation
  js/.changeset/nervous-penguins-camp.md
  js/.eslintrc.js
  js/examples/langchain-express/README.md
  js/examples/langchain-express/backend/.eslintrc.json
  js/examples/langchain-express/backend/.gitignore
  js/examples/langchain-express/backend/Dockerfile
  js/examples/langchain-express/backend/README.md
  js/examples/langchain-express/backend/index.ts
  js/examples/langchain-express/backend/instrumentation.ts
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/backend/package.json
  js/examples/langchain-express/backend/src/controllers/chat.controller.ts
  js/examples/langchain-express/backend/src/routes/chat.route.ts
  js/examples/langchain-express/backend/tsconfig.json
  js/examples/langchain-express/compose.yml
  js/examples/langchain-express/frontend/.env.example
  js/examples/langchain-express/frontend/.eslintrc.json
  js/examples/langchain-express/frontend/.gitignore
  js/examples/langchain-express/frontend/Dockerfile
  js/examples/langchain-express/frontend/README.md
  js/examples/langchain-express/frontend/app/components/chat-section.tsx
  js/examples/langchain-express/frontend/app/components/header.tsx
  js/examples/langchain-express/frontend/app/components/transform.ts
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-avatar.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-input.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-item.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-messages.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/index.ts
  js/examples/langchain-express/frontend/app/favicon.ico
  js/examples/langchain-express/frontend/app/globals.css
  js/examples/langchain-express/frontend/app/layout.tsx
  js/examples/langchain-express/frontend/app/page.tsx
  js/examples/langchain-express/frontend/next.config.js
  js/examples/langchain-express/frontend/package-lock.json
  js/examples/langchain-express/frontend/package.json
  js/examples/langchain-express/frontend/postcss.config.js
  js/examples/langchain-express/frontend/public/arize_logo.png
  js/examples/langchain-express/frontend/tailwind.config.ts
  js/examples/langchain-express/frontend/tsconfig.json
  js/packages/openinference-instrumentation-langchain/README.md
  js/packages/openinference-instrumentation-langchain/examples/chat.ts
  js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/jest.config.js
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/index.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/src/typeUtils.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/fixtures.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
  js/packages/openinference-instrumentation-langchain/tsconfig.esm.json
  js/packages/openinference-instrumentation-langchain/tsconfig.esnext.json
  js/packages/openinference-instrumentation-langchain/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XL, lgtm

#382 feat(langchainjs): add manual instrumentation method to langchain instrumentation
  js/.changeset/tiny-coins-knock.md
  js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
Labels: size:S, lgtm

#384 docs: wire up langchainjs example to new instrumentation
  js/examples/langchain-express/backend/instrumentation.ts
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/backend/package.json
Labels: size:XS, lgtm

#385 fix(langchainjs): update fallback span kind to be CHAIN
  js/.changeset/chatty-donuts-reflect.md
  js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/langchain.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
Labels: size:S, lgtm

#388 docs(langchainjs): update README to include manual instrumentation step
  js/.changeset/heavy-elephants-lay.md
  js/packages/openinference-instrumentation-langchain/README.md
  js/packages/openinference-instrumentation-langchain/examples/instrumentation.ts
Labels: size:S, lgtm

#387 feat(langchainjs): add rag example for LangChain.js auto instrumentation
  js/examples/langchain-express/README.md
  js/examples/langchain-express/backend/index.ts
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/backend/package.json
  js/examples/langchain-express/backend/src/constants.ts
  js/examples/langchain-express/backend/src/controllers/chat.controller.ts
  js/examples/langchain-express/backend/src/routes/chat.route.ts
  js/examples/langchain-express/backend/src/types.ts
  js/examples/langchain-express/backend/src/utils.ts
  js/examples/langchain-express/backend/src/vector_store/store.ts
  js/examples/langchain-express/frontend/app/components/chat-section.tsx
  js/examples/langchain-express/frontend/app/components/ui/chat/chat-input.tsx
Labels: size:L, lgtm

#390 docs: update readme to include LangChain.js instrumentation
  README.md
Labels: size:S, lgtm

#394 fix: convert numpy values for protobuf
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:S, lgtm

#396 docs: update LangChain.js instrumentation docs and improve rag in example
  README.md
  js/examples/langchain-express/backend/README.md
  js/examples/langchain-express/backend/src/constants.ts
  js/examples/langchain-express/backend/src/vector_store/store.ts
  js/packages/openinference-instrumentation-langchain/examples/README.md
Labels: size:M, lgtm

#397 chore: add symlinks to facilitate editable install
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/openinference-instrumentation/pyproject.toml
  python/openinference-instrumentation/src/openinference/instrumentation/bedrock
  python/openinference-instrumentation/src/openinference/instrumentation/dspy
  python/openinference-instrumentation/src/openinference/instrumentation/langchain
  python/openinference-instrumentation/src/openinference/instrumentation/llama_index
  python/openinference-instrumentation/src/openinference/instrumentation/mistralai
  python/openinference-instrumentation/src/openinference/instrumentation/openai
  python/openinference-semantic-conventions/pyproject.toml
  python/tox.ini
Labels: size:L, lgtm

#399 docs: fullstack dspy
  cspell.json
  python/examples/dspy-rag-fastapi/.gitignore
  python/examples/dspy-rag-fastapi/README.md
  python/examples/dspy-rag-fastapi/backend/Dockerfile
  python/examples/dspy-rag-fastapi/backend/app/__init__.py
  python/examples/dspy-rag-fastapi/backend/app/api/__init__.py
  python/examples/dspy-rag-fastapi/backend/app/api/routers/__init__.py
  python/examples/dspy-rag-fastapi/backend/app/api/routers/rag.py
  python/examples/dspy-rag-fastapi/backend/app/utils/__init__.py
  python/examples/dspy-rag-fastapi/backend/app/utils/load.py
  python/examples/dspy-rag-fastapi/backend/app/utils/models.py
  python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py
  python/examples/dspy-rag-fastapi/backend/app/utils/rag_modules.py
  python/examples/dspy-rag-fastapi/backend/data/example/paul_graham_essay.txt
  python/examples/dspy-rag-fastapi/backend/instrument.py
  python/examples/dspy-rag-fastapi/backend/main.py
  python/examples/dspy-rag-fastapi/backend/poetry.lock
  python/examples/dspy-rag-fastapi/backend/pyproject.toml
  python/examples/dspy-rag-fastapi/compose.yml
  python/examples/dspy-rag-fastapi/frontend/Dockerfile
  python/examples/dspy-rag-fastapi/frontend/about.py
  python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
  python/examples/dspy-rag-fastapi/frontend/poetry.lock
  python/examples/dspy-rag-fastapi/frontend/pyproject.toml
Labels: size:XXL, lgtm

#406 fix(dspy): dspy.Cohere
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_cohere.py
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_mistral.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
Labels: size:L

#407 docs(dspy): add support for cohere
  python/examples/dspy-rag-fastapi/README.md
  python/examples/dspy-rag-fastapi/backend/app/utils/models.py
  python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py
  python/examples/dspy-rag-fastapi/backend/poetry.lock
  python/examples/dspy-rag-fastapi/backend/pyproject.toml
  python/examples/dspy-rag-fastapi/compose.yml
  python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
Labels: size:M

#408 feat: Add `user.id` and `session.id` to semantic conventions
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:M, lgtm

#404 docs: switch dspy example to weaviate and cohere
  README.md
  cspell.json
  python/examples/README.md
  python/examples/dspy-rag-fastapi/.gitignore
  python/examples/dspy-rag-fastapi/README.md
  python/examples/dspy-rag-fastapi/backend/Dockerfile
  python/examples/dspy-rag-fastapi/backend/app/api/routers/rag.py
  python/examples/dspy-rag-fastapi/backend/app/utils/load.py
  python/examples/dspy-rag-fastapi/backend/app/utils/models.py
  python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py
  python/examples/dspy-rag-fastapi/backend/instrument.py
  python/examples/dspy-rag-fastapi/backend/main.py
  python/examples/dspy-rag-fastapi/backend/poetry.lock
  python/examples/dspy-rag-fastapi/backend/pyproject.toml
  python/examples/dspy-rag-fastapi/compose.yml
  python/examples/dspy-rag-fastapi/evaluation/evaluate.ipynb
  python/examples/dspy-rag-fastapi/frontend/about.py
  python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
Labels: size:XL, lgtm

#409 chore: Revert "feat: Add `user.id` and `session.id` to semantic conventions"
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:M, lgtm

#410 feat: Add `user.id` and `session.id` to semantic conventions
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:M, lgtm

#412 feat(js): session.id and user.id semantic conventions
  js/.changeset/tame-kids-yell.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:S, lgtm
