Repository Arize-ai/openinference, pull requests merged in 2024-11, with the labels that each got.

#1099 fix: defer version detection until run time for guardrails-ai
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/__init__.py
  python/instrumentation/openinference-instrumentation-guardrails/test-requirements.txt
  python/tox.ini
Labels: size:M, lgtm

#1105 feat(js): Add tool call id to semantic conventions and parse via instrumentation
  js/.changeset/cool-wasps-float.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  js/packages/openinference-vercel/src/AISemanticConventions.ts
  js/packages/openinference-vercel/src/constants.ts
  js/packages/openinference-vercel/src/utils.ts
  js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
Labels: size:M, lgtm

#1113 fix(dspy): instrument `dspy` rather than `dspy-ai`
  python/instrumentation/openinference-instrumentation-dspy/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/package.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:S, lgtm

#1112 fix: remove attaching and detaching of opentelemetry contexts
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
Labels: size:S, lgtm

#1120 chore(js): Fix langchain-express and llama-index-express docker examples
  js/examples/langchain-express/.env.example
  js/examples/langchain-express/README.md
  js/examples/langchain-express/backend/.dockerignore
  js/examples/langchain-express/backend/Dockerfile
  js/examples/langchain-express/compose.yml
  js/examples/langchain-express/frontend/.dockerignore
  js/examples/langchain-express/frontend/Dockerfile
  js/examples/llama-index-express/.env.example
  js/examples/llama-index-express/README.md
  js/examples/llama-index-express/backend/.dockerignore
  js/examples/llama-index-express/backend/Dockerfile
  js/examples/llama-index-express/compose.yml
  js/examples/llama-index-express/frontend/.dockerignore
  js/examples/llama-index-express/frontend/Dockerfile
Labels: size:M, lgtm

#1121 fix(js): set spans from instrumentation active span on context in OpenAI instrumentor
  js/.changeset/dirty-candles-brake.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
Labels: size:S, lgtm

#1122 chore: remove non-existent `llm.provider` value from markdown table
  spec/semantic_conventions.md
Labels: size:XS, lgtm

#1123 fix(langchain-js): add token counts for ChatBedrock models
  js/.changeset/mean-walls-talk.md
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
Labels: size:L

#1126 chore(examples): update openai example packages and dockerfiles
  js/examples/openai/backend/.dockerignore
  js/examples/openai/backend/Dockerfile
  js/examples/openai/backend/package.json
  js/examples/openai/compose.yml
  js/examples/openai/frontend/.dockerignore
  js/examples/openai/frontend/Dockerfile
  js/examples/openai/frontend/package.json
Labels: size:S

#1124 fix: capture anthropic model name from response
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_messages.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:S

#1129 fix: add tool id for anthropic instrumentor and serialize `content` to string if it's not a string
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
Labels: size:M

#1131 feat: add google as provider for openai instrumentor
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
Labels: size:XS
