Repository Arize-ai/openinference, pull requests merged in 2024-12, with the labels that each got.

#1137 fix: relax python upperbound for openinference-instrumentation
  python/openinference-instrumentation/pyproject.toml
  python/tox.ini
Labels: size:XS

#1141 docs: fix broken imports and add links for openinference-core
  README.md
  js/packages/openinference-core/README.md
Labels: size:XS

#1142 docs: instrument llama-index example for sessions
  python/examples/llama-index/backend/app/api/routers/chat.py
  python/examples/llama-index/backend/instrument.py
  python/examples/llama-index/compose.yaml
  python/examples/llama-index/frontend/app/components/chat-section.tsx
  python/examples/llama-index/frontend/package-lock.json
Labels: size:M

#1151 feat(js): add session id parsing to langchain instrumentation
  js/.changeset/shaggy-goats-love.md
  js/packages/openinference-instrumentation-langchain/examples/chat.ts
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV1.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts
Labels: size:L

#1153 feat(semcov): audio conventions
  js/.changeset/mighty-mangos-search.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:M

#1157 ci: restrict httpx version <0.28
  python/tox.ini
Labels: size:S

#1156 chore: remove llamaindex npm package
  js/packages/openinference-instrumentation-llama-index/CHANGELOG.md
  js/packages/openinference-instrumentation-llama-index/README.md
  js/packages/openinference-instrumentation-llama-index/jest.config.js
  js/packages/openinference-instrumentation-llama-index/package.json
  js/packages/openinference-instrumentation-llama-index/src/index.ts
  js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
  js/packages/openinference-instrumentation-llama-index/tsconfig.esm.json
  js/packages/openinference-instrumentation-llama-index/tsconfig.esnext.json
  js/packages/openinference-instrumentation-llama-index/tsconfig.json
Labels: size:L

#1159 fix: update lock file after removal of llamaindex package
  js/pnpm-lock.yaml
Labels: size:XS

#1162 chore(js): Update quick start dependency list
  js/README.md
Labels: size:XS

#1164 ci: fix type check for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/tox.ini
Labels: size:XS

#1166 fix: handle multiple embedding events for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/conftest.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_multiple_embedding_events.py
Labels: size:M

#1163 feat(js): Fix ESM builds
  js/.changeset/smart-donuts-attack.md
  js/package.json
  js/packages/openinference-core/package.json
  js/packages/openinference-core/src/index.ts
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-openai/package.json
  js/packages/openinference-semantic-conventions/package.json
  js/packages/openinference-vercel/package.json
  js/pnpm-lock.yaml
  js/tsconfig.base.esm.json
Labels: size:M

#1165 feat: add get_current_span helper function for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_get_current_span.py
Labels: size:M

#1161 docs: update `CONTRIBUTING.md` to point to the correct file
  python/examples/README.md
Labels: size:XS

#1171 feat: add ability to hide LLM invocation paramaters for OITracer
  python/openinference-instrumentation/pyproject.toml
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/test_config.py
Labels: size:M

#1174 fix(llama-index): extract token counts for groq when streaming
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/test_groq_astream_chat_token_count.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_token_counts.py
  python/tox.ini
Labels: size:L

#1177 fix(llama-index): capture tool calls from anthropic chat response
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestToolCallsInChatResponse.test_anthropic.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestToolCallsInChatResponse.test_openai.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_multimodal.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_tool_calls_response.py
  python/tox.ini
Labels: size:L

#1133 feat(groq): refactor groq, add groq tool call support
  python/instrumentation/openinference-instrumentation-groq/examples/chat_completions_with_tool.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/__init__.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_utils.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_wrappers.py
  python/instrumentation/openinference-instrumentation-groq/tests/conftest.py
  python/instrumentation/openinference-instrumentation-groq/tests/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-groq/tests/test_tool_calls.py
Labels: size:XL

#1180 chore: Adjust llm.tools semantic convention example
  spec/semantic_conventions.md
Labels: size:S
