Repository Arize-ai/openinference, pull requests merged in 2024-08, with the labels that each got.

#686 feat(vertexai): Enable configuration using common instrumentation pkg
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/__init__.py
  python/instrumentation/openinference-instrumentation-vertexai/tests/test_gapic_client.py
Labels: size:L, lgtm

#685 feat(langchain): Enable configuration using common instrumentation pkg
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_config.py
Labels: size:L, lgtm

#669 fix: add token counts for langchain streaming
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_records_token_counts_for_streaming_openai_llm.yaml
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:L, lgtm

#695 chore: fix typo for haystack-ai
  python/instrumentation/openinference-instrumentation-haystack/README.md
  python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt
Labels: size:XS, lgtm

#693 fix: Rename base tracer and masked span
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/__init__.py
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/src/openinference/instrumentation/version.py
Labels: size:M, lgtm

#643 feat(js): llama-index-ts initial retrieval span support
  js/packages/openinference-instrumentation-llama-index/src/instrumentation.ts
  js/packages/openinference-instrumentation-llama-index/src/types.ts
  js/packages/openinference-instrumentation-llama-index/src/utils.ts
  js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
Labels: size:L

#701 fix(haystack): tweak setting of attributes
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:M, lgtm

#706 chore: add symlinks to new libs for editable install
  python/openinference-instrumentation/src/openinference/instrumentation/crewai
  python/openinference-instrumentation/src/openinference/instrumentation/haystack
  python/openinference-instrumentation/src/openinference/instrumentation/litellm
Labels: size:XS, lgtm

#694 feat(groq): instrumentation
  python/instrumentation/openinference-instrumentation-groq/LICENSE
  python/instrumentation/openinference-instrumentation-groq/README.md
  python/instrumentation/openinference-instrumentation-groq/examples/async_chat_completions.py
  python/instrumentation/openinference-instrumentation-groq/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/__init__.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_wrappers.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/version.py
  python/instrumentation/openinference-instrumentation-groq/tests/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#739 fix: set higher lower-bound for OpenInference dependency
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
Labels: size:XS, lgtm

#741 feat: Enable config propagation
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/__init__.py
  python/instrumentation/openinference-instrumentation-guardrails/tests/openinference/instrumentation/guardrails/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:L, lgtm

#738 feat(groq): add to README and release please for groq
  README.md
  release-please-config.json
Labels: size:S, lgtm

#705 fix(haystack): keep ruff guides consistent across instrumentors
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:M, lgtm

#751 docs: update openai readme
  python/instrumentation/openinference-instrumentation-openai/README.md
Labels: size:XS, lgtm

#750 feat(promptflow): Added prompt flow example guide
  python/instrumentation/openinference-instrumentation-promptflow/examples/chat.prompty
  python/instrumentation/openinference-instrumentation-promptflow/examples/chat_flow_example.ipynb
  python/instrumentation/openinference-instrumentation-promptflow/examples/flow.py
Labels: size:L, lgtm

#754 docs: update openai readme
  python/instrumentation/openinference-instrumentation-openai/README.md
Labels: size:XS, lgtm

#755 feat(haystack): Support context attribute propagation
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:L, lgtm

#759 feat(promptflow): Added prompt flow example that exports traces to Arize
  python/instrumentation/openinference-instrumentation-promptflow/examples/chat_flow_example_to_arize.ipynb
  python/instrumentation/openinference-instrumentation-promptflow/examples/chat_flow_example_to_phoenix.ipynb
  python/instrumentation/openinference-instrumentation-promptflow/examples/flow.py
Labels: size:L, lgtm

#769 fix: ignore `WorkflowDone` exception
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/examples/workflow.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:M, lgtm

#770 feat(semantic-conventions): add reranker, metadata, tag, and tool parameters to semantic conventions
  js/.changeset/good-avocados-sell.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:M, lgtm

#760 feat(haystack): Add support for ChatPromptBuilder and ChatOpenAIGenerator components
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:L, lgtm

#773 fix(llama-index): Adjust newspan args in BaseHandler
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:XS, lgtm

#777 feat: TraceConfig and context attribute support
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/__init__.py
  python/instrumentation/openinference-instrumentation-groq/src/openinference/instrumentation/groq/_wrappers.py
  python/instrumentation/openinference-instrumentation-groq/tests/test_instrumentor.py
Labels: size:L, lgtm

#691 feat(instructor): instrumentation
  python/instrumentation/openinference-instrumentation-instructor/LICENSE
  python/instrumentation/openinference-instrumentation-instructor/README.md
  python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
  python/instrumentation/openinference-instrumentation-instructor/src/openinference/instrumentation/instructor/__init__.py
  python/instrumentation/openinference-instrumentation-instructor/src/openinference/instrumentation/instructor/_wrappers.py
  python/instrumentation/openinference-instrumentation-instructor/src/openinference/instrumentation/instructor/version.py
  python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/fixtures/async_instructor_instrumentation.yaml
  python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/fixtures/instructor_instrumentation.yaml
  python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/fixtures/streaming.yaml
  python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/test_instrumentation.py
  python/tox.ini
Labels: size:XL, lgtm

#783 feat(instructor): release please for instructor
  README.md
  release-please-config.json
Labels: size:XS, lgtm

#781 test: add tests for haystack
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:M, lgtm

#753 feat: Capture images tracing converse API
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_converse.py
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_multimodal.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
Labels: size:L, lgtm

#791 chore: fix typos in README
  README.md
Labels: size:XS, lgtm

#782 feat(openinference-core): add support for userId, attributes, and tags
  js/packages/openinference-core/src/trace/contextAttributes.ts
  js/packages/openinference-core/src/trace/index.ts
  js/packages/openinference-core/src/trace/types.ts
  js/packages/openinference-core/src/utils/index.ts
  js/packages/openinference-core/src/utils/typeUtils.ts
  js/packages/openinference-core/test/trace/contextAttributes.test.ts
Labels: size:L, lgtm

#358 feat(js): openinference-core
  js/.changeset/early-lobsters-cough.md
  js/packages/openinference-core/README.md
  js/packages/openinference-core/jest.config.js
  js/packages/openinference-core/package.json
  js/packages/openinference-core/src/index.ts
  js/packages/openinference-core/src/trace/contextAttributes.ts
  js/packages/openinference-core/src/trace/index.ts
  js/packages/openinference-core/src/trace/session.ts
  js/packages/openinference-core/src/trace/types.ts
  js/packages/openinference-core/src/utils/index.ts
  js/packages/openinference-core/src/utils/typeUtils.ts
  js/packages/openinference-core/src/utils/types.ts
  js/packages/openinference-core/test/trace/contextAttributes.test.ts
  js/packages/openinference-core/test/utils/typeUtils.test.ts
  js/packages/openinference-core/tsconfig.esm.json
  js/packages/openinference-core/tsconfig.esnext.json
  js/packages/openinference-core/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XL, feature branch

#793 docs: TraceConfig and context attributes
  python/README.md
  python/instrumentation/openinference-instrumentation-bedrock/README.md
  python/instrumentation/openinference-instrumentation-crewai/README.md
  python/instrumentation/openinference-instrumentation-dspy/README.md
  python/instrumentation/openinference-instrumentation-groq/README.md
  python/instrumentation/openinference-instrumentation-guardrails/README.md
  python/instrumentation/openinference-instrumentation-haystack/README.md
  python/instrumentation/openinference-instrumentation-instructor/README.md
  python/instrumentation/openinference-instrumentation-langchain/README.md
  python/instrumentation/openinference-instrumentation-litellm/README.md
  python/instrumentation/openinference-instrumentation-llama-index/README.md
  python/instrumentation/openinference-instrumentation-mistralai/README.md
  python/instrumentation/openinference-instrumentation-openai/README.md
  python/instrumentation/openinference-instrumentation-vertexai/README.md
  python/openinference-instrumentation/README.md
  spec/README.md
Labels: size:L, lgtm

#810 fix: bump minimum version for openinference-instrumentation
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
Labels: size:XS, lgtm

#808 chore: add example for haystack
  python/instrumentation/openinference-instrumentation-haystack/examples/filtering_documents_with_metadata.py
Labels: size:M, lgtm

#809 docs(haystack): web questions example
  python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-haystack/examples/web_questions.py
Labels: size:M, lgtm

#816 chore: fix formatting
  python/instrumentation/openinference-instrumentation-haystack/examples/filtering_documents_with_metadata.py
Labels: size:XS, lgtm

#811 chore: add haystack example
  python/instrumentation/openinference-instrumentation-haystack/examples/building_fallbacks_with_conditional_routing.py
Labels: size:L, lgtm

#817 chore: revert instrumentation pip install
  python/tox.ini
Labels: size:XS, lgtm

#819 docs: Update DEVELOPEMENT.md guide
  python/DEVELOPMENT.md
Labels: size:L, lgtm

#827 feat(semconv): export image semantic conventions
  js/.changeset/large-berries-promise.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:S, lgtm

#818 fix: Setting of attributes crashes Phoenix and default some components to chain
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:L, lgtm

#812 docs(haystack): add rag example from haystack
  python/instrumentation/openinference-instrumentation-haystack/examples/haystack_rag_pipeline.py
Labels: size:M, lgtm

#761 feat(js): llama-index-ts embeddings support
  js/packages/openinference-instrumentation-llama-index/package.json
  js/packages/openinference-instrumentation-llama-index/src/instrumentation.ts
  js/packages/openinference-instrumentation-llama-index/src/types.ts
  js/packages/openinference-instrumentation-llama-index/src/utils.ts
  js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
  js/packages/openinference-instrumentation-llama-index/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XL, lgtm

#831 chore: upgrade python tooling
  .github/workflows/python-CI.yaml
  python/dev-requirements.txt
Labels: size:M, lgtm

#837 fix(haystack): Adjust LLM message attributes for Haystack instrumentation to match semantic conventions
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_openai_chat_generator_llm_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_openai_generator_llm_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:L, lgtm

#828 feat(openai): capture images in request
  js/.changeset/mighty-adults-bake.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
Labels: size:L, lgtm

#840 ci: Update python-CI.yaml to run on: oss-4-core-runner
  .github/workflows/python-CI.yaml
Labels: size:XS, lgtm

#779 feat(liteLLM): LiteLLM trace config and context attributes propagation
  python/instrumentation/openinference-instrumentation-litellm/guides/client_demo.ipynb
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/package.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#846 chore(python): more efficient CI workflow
  .github/workflows/python-CI.yaml
  .github/workflows/python-cron.yaml
  python/DEVELOPMENT.md
  python/dev-requirements.txt
  python/tox.ini
Labels: size:L, lgtm

#856 ci: add uv as a dev requirement
  python/dev-requirements.txt
Labels: size:XS, lgtm

#839 feat: Tool calling support for HaystackInstrumentor
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_haystack_tool_calling_llm_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:L, lgtm

#854 ci(python): add slack notification for failed cron job
  .github/workflows/python-cron.yaml
Labels: size:S, lgtm

#858 ci: revert uv dev req
  python/dev-requirements.txt
Labels: size:XS, lgtm

#859 ci(python): replace newline with (markdown) backslash
  .github/workflows/python-cron.yaml
Labels: size:XS, lgtm

#860 ci(python): remove backslash in bash command
  .github/workflows/python-cron.yaml
Labels: size:S, lgtm

#861 ci(python): remove blocks from slack payload
  .github/workflows/python-cron.yaml
Labels: size:S, lgtm

#862 ci: ensure `uv` installs local libraries in editable mode
  python/tox.ini
Labels: size:M, lgtm

#863 ci(python): replace editable install with reinstall
  python/tox.ini
Labels: size:M, lgtm

#864 ci: fix metadata for langchain-latest
  .github/workflows/python-CI.yaml
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:S, lgtm

#851 feat(crewAI): Added trace config, context attributes, suppress tracing for CrewAI
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/__init__.py
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
Labels: size:L, lgtm

#868 ci(python): rich text for slack
  .github/workflows/python-cron.yaml
Labels: size:M, lgtm

#873 revert: "ci(python): rich text for slack"
  .github/workflows/python-cron.yaml
Labels: size:M, lgtm

#874 ci: update tox-uv
  .github/workflows/python-CI.yaml
  .github/workflows/python-cron.yaml
  python/DEVELOPMENT.md
Labels: size:XS, lgtm

#844 fix: implement prompt template attributes for prompt builder and add helper functions
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_serperdev_websearch_retriever_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:XL, lgtm

#875 docs(examples): move phoenix image version to latest for openai example
  js/examples/langchain-express/compose.yml
  js/examples/llama-index-express/compose.yml
  js/examples/openai/compose.yml
Labels: size:XS, lgtm

#876 fix: haystack tool calling for `OpenAIChatGenerator`
  python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-haystack/examples/tool_calling.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_pipeline_and_component_spans_contain_context_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_pipelines_and_components_produce_no_tracing_with_suppress_tracing.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_tool_calling_llm_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:XL, lgtm

#896 ci(openai): fix test for hide inputs
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:S, lgtm

#894 feat: add re-ranker support in haystack
  python/instrumentation/openinference-instrumentation-haystack/examples/cohere_reranker.py
  python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_cohere_reranker_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_error_status_code_and_exception_events_with_invalid_api_key.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
  python/tox.ini
Labels: size:L, lgtm

#903 fix(haystack): improve span names and mask output embeddings
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_pipeline_with_chat_prompt_builder_and_chat_generator_produces_expected_spans.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
  python/tox.ini
Labels: size:L, lgtm

#912 ci: limit mistralai < 1
  python/tox.ini
Labels: size:XS, lgtm

#904 feat: Added tools attribute
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/conftest.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_tool_calls.py
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
Labels: size:L, lgtm

#906 feat: attribute prioritization
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/conftest.py
  python/openinference-instrumentation/tests/test_config.py
Labels: size:L, lgtm

#917 fix(haystack): ensure important attributes such as span kind are not lost
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
Labels: size:XS, lgtm

#918 chore: increase byte-allowance for image examples
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_multimodal_with_config.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/image_upload.py
Labels: size:S, lgtm

#855 docs(vercel-ai-sdk): add example for instrumentation with vercel ai sdk
  js/examples/next-openai-telemetry-app/.env.local.example
  js/examples/next-openai-telemetry-app/.gitignore
  js/examples/next-openai-telemetry-app/README.md
  js/examples/next-openai-telemetry-app/app/api/text/route.ts
  js/examples/next-openai-telemetry-app/app/favicon.ico
  js/examples/next-openai-telemetry-app/app/globals.css
  js/examples/next-openai-telemetry-app/app/layout.tsx
  js/examples/next-openai-telemetry-app/app/page.tsx
  js/examples/next-openai-telemetry-app/instrumentation.ts
  js/examples/next-openai-telemetry-app/next.config.js
  js/examples/next-openai-telemetry-app/package.json
  js/examples/next-openai-telemetry-app/pnpm-lock.yaml
  js/examples/next-openai-telemetry-app/postcss.config.js
  js/examples/next-openai-telemetry-app/tailwind.config.js
  js/examples/next-openai-telemetry-app/tsconfig.json
Labels: size:L, lgtm

#919 fix(haystack): improve heuristic for identifying component type
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
Labels: size:S, lgtm

#921 feat(core): export withSafety utilities remove custom `isAttributeValue` to use @opentelemetry/core's
  js/.changeset/stale-geckos-hear.md
  js/packages/openinference-core/package.json
  js/packages/openinference-core/src/index.ts
  js/packages/openinference-core/src/trace/contextAttributes.ts
  js/packages/openinference-core/src/utils/typeUtils.ts
  js/packages/openinference-core/test/utils/typeUtils.test.ts
  js/pnpm-lock.yaml
Labels: size:L, lgtm

#920 chore: Added tool definitions to semantic_conventions.md
  spec/semantic_conventions.md
Labels: size:XS, lgtm

#900 feat(liteLLM): Implemented image support and corresponding tests
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-litellm/guides/client_demo.ipynb
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
Labels: size:L, lgtm

#878 feat: Anthropic instrumentation
  python/instrumentation/openinference-instrumentation-anthropic/LICENSE
  python/instrumentation/openinference-instrumentation-anthropic/README.md
  python/instrumentation/openinference-instrumentation-anthropic/examples/sync_completions.py
  python/instrumentation/openinference-instrumentation-anthropic/examples/sync_messages.py
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/__init__.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/version.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_async_completions.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_async_messages.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_completions.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_context_attributes_existence.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_messages.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
  python/tox.ini
Labels: size:XXL, lgtm

#926 fix(langchainjs): account for non-mutabable package installs for langchain
  js/.changeset/tasty-numbers-try.md
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
Labels: size:M, lgtm

#925 feat: add README and release please for anthropic instrumentor
  README.md
  python/instrumentation/openinference-instrumentation-anthropic/README.md
  release-please-config.json
Labels: size:M, lgtm

#932 chore: Tweaked README to fix link to package
  README.md
Labels: size:XS, lgtm

#934 fix(dspy): module resolution for custom LM
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_custom_lm.py
  python/instrumentation/openinference-instrumentation-dspy/examples/lm/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/examples/lm/custom_lm.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
Labels: size:M, lgtm

#867 feat(crewai): Add SpanKind and Token Count attributes
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session_context_attributes.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
Labels: size:L, lgtm

#879 feat(vercel-ai-sdk): add span exporter to append open inference attributes to vercel created spans
  js/.changeset/red-mayflies-rescue.md
  js/examples/README.md
  js/examples/next-openai-telemetry-app/.env.local.example
  js/examples/next-openai-telemetry-app/app/api/text/route.ts
  js/examples/next-openai-telemetry-app/instrumentation.ts
  js/examples/next-openai-telemetry-app/package.json
  js/examples/next-openai-telemetry-app/pnpm-lock.yaml
  js/package.json
  js/packages/openinference-vercel/README.md
  js/packages/openinference-vercel/jest.config.js
  js/packages/openinference-vercel/package.json
  js/packages/openinference-vercel/src/AISemanticConventions.ts
  js/packages/openinference-vercel/src/OpenInferenceSpanProcessor.ts
  js/packages/openinference-vercel/src/constants.ts
  js/packages/openinference-vercel/src/index.ts
  js/packages/openinference-vercel/src/typeUtils.ts
  js/packages/openinference-vercel/src/types.ts
  js/packages/openinference-vercel/src/utils.ts
  js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
  js/packages/openinference-vercel/tsconfig.esm.json
  js/packages/openinference-vercel/tsconfig.esnext.json
  js/packages/openinference-vercel/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XXL, lgtm

#936 feat(js): Added tools and tool_json_schema definitions to js semantic conventions
  js/.changeset/fresh-seals-judge.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:S, lgtm

#935 ci(python): fail fast
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
  python/openinference-instrumentation/pyproject.toml
  python/openinference-semantic-conventions/pyproject.toml
  python/tox.ini
Labels: size:M, lgtm

#938 docs(examples): update vercel ai sdk example to have a chat interface
  js/examples/next-openai-telemetry-app/.env.local.example
  js/examples/next-openai-telemetry-app/README.md
  js/examples/next-openai-telemetry-app/app/api/chat/route.ts
  js/examples/next-openai-telemetry-app/app/api/text/route.ts
  js/examples/next-openai-telemetry-app/app/components/chat-section.tsx
  js/examples/next-openai-telemetry-app/app/components/header.tsx
  js/examples/next-openai-telemetry-app/app/components/transform.ts
  js/examples/next-openai-telemetry-app/app/components/ui/chat/chat-avatar.tsx
  js/examples/next-openai-telemetry-app/app/components/ui/chat/chat-input.tsx
  js/examples/next-openai-telemetry-app/app/components/ui/chat/chat-item.tsx
  js/examples/next-openai-telemetry-app/app/components/ui/chat/chat-messages.tsx
  js/examples/next-openai-telemetry-app/app/components/ui/chat/index.ts
  js/examples/next-openai-telemetry-app/app/favicon.ico
  js/examples/next-openai-telemetry-app/app/globals.css
  js/examples/next-openai-telemetry-app/app/layout.tsx
  js/examples/next-openai-telemetry-app/app/page.tsx
  js/examples/next-openai-telemetry-app/instrumentation.ts
  js/examples/next-openai-telemetry-app/package.json
  js/examples/next-openai-telemetry-app/pnpm-lock.yaml
  js/examples/next-openai-telemetry-app/public/arize_logo.png
  js/examples/next-openai-telemetry-app/tailwind.config.js
  js/examples/next-openai-telemetry-app/tailwind.config.ts
Labels: size:XL, lgtm

#939 feat: Tool calling for Anthropic instrumentor
  python/instrumentation/openinference-instrumentation-anthropic/examples/multiple_tool_calling.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_multiple_tool_calling.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:L, lgtm

#942 feat(js): Added tool logic to openAI instrumentation and modified test accordingly
  js/.changeset/stale-teachers-decide.md
  js/packages/openinference-instrumentation-openai/package.json
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/pnpm-lock.yaml
Labels: size:L, lgtm

#945 chore(anthropic): add example and requirements file for anthropic examples
  python/instrumentation/openinference-instrumentation-anthropic/examples/end_to_end_tool_use.py
  python/instrumentation/openinference-instrumentation-anthropic/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
Labels: size:L, lgtm

#941 feat(guardrails): limit support to versions <0.5.2
  python/instrumentation/openinference-instrumentation-guardrails/README.md
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/__init__.py
  python/tox.ini
Labels: size:S, lgtm

#946 chore: update pnpm version and pin in package.json
  .github/workflows/typescript-CI.yaml
  .github/workflows/typescript-publish.yaml
  .gitignore
  js/.npmrc
  js/DEVELOPMENT.md
  js/package.json
  js/pnpm-lock.yaml
Labels: size:XS, lgtm

#949 fix(vercel): add input / output to tool spans, remove duplicate token counts
  js/.changeset/young-horses-grab.md
  js/packages/openinference-vercel/src/AISemanticConventions.ts
  js/packages/openinference-vercel/src/constants.ts
  js/packages/openinference-vercel/src/utils.ts
  js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
Labels: size:L, lgtm

#952 feat(core): remove automatic loggin in withSafety function
  js/.changeset/violet-turtles-yawn.md
  js/packages/openinference-core/src/utils/index.ts
  js/packages/openinference-core/test/trace/utils.test.ts
  js/packages/openinference-vercel/src/utils.ts
Labels: size:L, lgtm

#959 fix(haystack): ensure haystack is not a runtime dependency
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
Labels: size:M, lgtm

#961 fix(haystack): remove remaining haystack import
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
Labels: size:XS, lgtm

#971 fix(llama-index): Follow naming convention of private attributes
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/README.md
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_multimodal.py
Labels: size:M, lgtm

#963 feat(langchainjs): support langchain `^0.2.0`
  js/.changeset/silver-rockets-cough.md
  js/package.json
  js/packages/openinference-instrumentation-langchain/examples/chat.ts
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentationUtils.ts
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/instrumentationUtils.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV1.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts
  js/packages/openinference-instrumentation-langchain/test/utils.test.ts
  js/packages/openinference-instrumentation-langchain/tsconfig.esm.json
  js/packages/openinference-instrumentation-langchain/tsconfig.esnext.json
  js/packages/openinference-instrumentation-langchain/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XXL, lgtm

#974 docs(examples): update langchain express example to langchain v0.2.x
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/backend/package.json
  js/examples/langchain-express/backend/src/controllers/chat.controller.ts
Labels: size:S, lgtm

#975 fix(bedrock): ensure bedrock instrumentation does not break runtime for BedrockEmbeddings model from langchain
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
Labels: size:XS, lgtm

#978 ci: Deploy setup for vercel telemetry
  cspell.json
  js/examples/next-openai-telemetry-app/.env.local.example
  js/examples/next-openai-telemetry-app/README.md
  js/examples/next-openai-telemetry-app/instrumentation.ts
  js/examples/next-openai-telemetry-app/package-lock.json
  js/examples/next-openai-telemetry-app/package.json
  js/examples/next-openai-telemetry-app/pnpm-lock.yaml
Labels: size:S, lgtm

#948 fix: Fix input message attribute issues + toolcalling from dogfooding
  python/instrumentation/openinference-instrumentation-anthropic/examples/end_to_end_tool_use.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_tool_use_in_input[with_block_params].yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_tool_use_in_input[with_blocks].yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:L, lgtm

#681 docs: litellm examples
  README.md
  cspell.json
  python/instrumentation/openinference-instrumentation-litellm/README.md
  python/instrumentation/openinference-instrumentation-litellm/examples/litellm-proxy/README.md
  python/instrumentation/openinference-instrumentation-litellm/examples/litellm.py
Labels: size:L, lgtm

#992 docs: update vercel example to use 1.0 span processor
  js/examples/next-openai-telemetry-app/instrumentation.ts
  js/examples/next-openai-telemetry-app/package-lock.json
  js/examples/next-openai-telemetry-app/package.json
Labels: size:S

#993 docs: vercel README
  README.md
  js/.changeset/violet-books-agree.md
  js/packages/openinference-vercel/README.md
Labels: size:L
