Repository Arize-ai/openinference, pull requests merged in 2024-03, with the labels that each got.

#251 chore: upgrade ruff to 0.3.0
  python/dev-requirements.txt
  python/examples/llama-index/backend/main.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_stream.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_version.py
  python/ruff.toml
Labels: size:M, lgtm

#250 fix: support dpsy 2.3.4 and above
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:L, lgtm

#249 fix: concurrent tracing for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
Labels: size:L, lgtm

#255 fix: add support for DSPy's Google model class
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:M, lgtm

#253 feat: add resource attributes to semantic conventions
  python/openinference-semantic-conventions/src/openinference/semconv/resource/__init__.py
Labels: size:XS, lgtm

#261 feat: allow dspy instrumentation to be suppressed
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
Labels: size:S, lgtm

#234 fix: metadata as json string in langchain instrumentor
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:XS, lgtm

#264 chore: add example for langserve
  python/examples/langserve/per_request_metadata.py
Labels: size:M, lgtm

#270 fix: Add token counts to bedrock instrumentation
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
Labels: size:M, lgtm

#271 feat: add support for python 3.12
  .github/workflows/python-CI.yaml
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/tox.ini
Labels: size:M, lgtm

#279 fix: dspy instrumentation does not break teleprompter compilation
  python/instrumentation/openinference-instrumentation-dspy/.gitignore
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:L, lgtm

#284 chore: revert arize setup
  cspell.json
  js/examples/openai/src/instrumentation.ts
Labels: size:XS

#285 docs: quick start demo for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/README.md
Labels: size:M, lgtm

#292 fix: for streaming use `response_txt` as output_value for llama-index
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:XS, lgtm

#278 docs: Improve README
  python/instrumentation/openinference-instrumentation-bedrock/README.md
Labels: size:M, lgtm

#290 docs(openai): flesh out README
  python/instrumentation/openinference-instrumentation-openai/README.md
Labels: size:M, lgtm

#296 docs: make examples more prominent
  README.md
  js/examples/README.md
  python/examples/README.md
Labels: size:M, lgtm

#297 docs: improve dspy readme
  python/instrumentation/openinference-instrumentation-dspy/README.md
Labels: size:M, lgtm

#302 fix: allow running handler in threads
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:M, lgtm

#301 fix: add printer for run times
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:S, lgtm

#304 fix: use start and end times from langchain
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:S, lgtm

#300 feat: mistral ai instrumentation for synchronous chat completions
  .gitignore
  python/instrumentation/openinference-instrumentation-mistralai/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-mistralai/LICENSE
  python/instrumentation/openinference-instrumentation-mistralai/README.md
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-mistralai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_sync_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_with_span.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/package.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/py.typed
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/version.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/openai/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#309 chore: add mistralai to release-please manifest
  .release-please-manifest.json
Labels: size:S, lgtm

#308 chore: add test case for sync chat completions
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:M, lgtm

#313 feat: add tool calling support for sync and async chat completions for mistralai instrumentation
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_function_calling.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_function_calling.py
  python/tox.ini
Labels: size:XL, lgtm

#323 fix: mistral argument parsing error
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:M, lgtm

#327 docs: Update MistralAI instrumentation documentation
  README.md
  python/instrumentation/openinference-instrumentation-mistralai/README.md
Labels: size:M, lgtm

#326 feat: add support for sync streaming to mistralai
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_streaming.py
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_stream.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:XL, lgtm

#329 feat: support async streaming chat completions for mistralai
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_async_streaming.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:L, lgtm

#332 fix: support streaming with tool calls
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_streaming_with_function_calling.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:L, lgtm

#334 docs: update mistral README.md with pypi badge
  python/instrumentation/openinference-instrumentation-mistralai/README.md
Labels: size:XS

#339 docs: document process for creating a new conda feedstock
  python/DEVELOPMENT.md
Labels: size:M, lgtm

#341 fix: update mistralai minimum python version
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
Labels: size:XS, lgtm

#340 feat: add openinference-instrumentation package
  python/openinference-instrumentation/README.md
  python/openinference-instrumentation/pyproject.toml
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/py.typed
  python/openinference-instrumentation/src/openinference/instrumentation/version.py
  python/openinference-instrumentation/tests/test_suppress_tracing.py
  python/tox.ini
  release-please-config.json
Labels: size:L, lgtm

#344 fix: add license file for openinference-instrumentation
  python/openinference-instrumentation/LICENSE
Labels: size:XS, lgtm

#347 feat: move openai example to express
  js/examples/openai/README.md
  js/examples/openai/backend/.eslintrc.json
  js/examples/openai/backend/.gitignore
  js/examples/openai/backend/Dockerfile
  js/examples/openai/backend/README.md
  js/examples/openai/backend/index.ts
  js/examples/openai/backend/instrumentation.ts
  js/examples/openai/backend/package-lock.json
  js/examples/openai/backend/package.json
  js/examples/openai/backend/src/controllers/chat.controller.ts
  js/examples/openai/backend/src/routes/chat.route.ts
  js/examples/openai/backend/tsconfig.json
  js/examples/openai/compose.yml
  js/examples/openai/frontend/.env.example
  js/examples/openai/frontend/.eslintrc.json
  js/examples/openai/frontend/.gitignore
  js/examples/openai/frontend/Dockerfile
  js/examples/openai/frontend/README.md
  js/examples/openai/frontend/app/components/chat-section.tsx
  js/examples/openai/frontend/app/components/header.tsx
  js/examples/openai/frontend/app/components/transform.ts
  js/examples/openai/frontend/app/components/ui/chat/chat-avatar.tsx
  js/examples/openai/frontend/app/components/ui/chat/chat-input.tsx
  js/examples/openai/frontend/app/components/ui/chat/chat-item.tsx
  js/examples/openai/frontend/app/components/ui/chat/chat-messages.tsx
  js/examples/openai/frontend/app/components/ui/chat/index.ts
  js/examples/openai/frontend/app/favicon.ico
  js/examples/openai/frontend/app/globals.css
  js/examples/openai/frontend/app/layout.tsx
  js/examples/openai/frontend/app/page.tsx
  js/examples/openai/frontend/next.config.js
  js/examples/openai/frontend/package-lock.json
  js/examples/openai/frontend/package.json
  js/examples/openai/frontend/postcss.config.js
  js/examples/openai/frontend/public/arize_logo.png
  js/examples/openai/frontend/tailwind.config.ts
  js/examples/openai/frontend/tsconfig.json
  js/examples/openai/package-lock.json
  js/examples/openai/package.json
  js/examples/openai/src/index.ts
  js/examples/openai/tsconfig.json
Labels: size:XL, lgtm

#349 docs: Update LangChain instrumentation readme
  python/instrumentation/openinference-instrumentation-langchain/README.md
Labels: size:M, lgtm
