Repository Arize-ai/openinference, pull requests merged in 2024-02, with the labels that each got.

#158 feat: dspy instrumentation enhancements
  python/.gitignore
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-dspy/examples/rag_module.py
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XL, lgtm

#166 docs: add examples, supported destinations, and community links to readme
  README.md
Labels: size:M, lgtm

#168 docs(js): enhance js readme
  js/README.md
Labels: size:S

#165 docs: Improve Python LlamaIndex example documentation
  python/examples/llama-index/README.md
Labels: size:M, lgtm

#157 fix: JSON string attributes
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:M, lgtm

#176 feat(semcov): add metadata
  js/.changeset/cuddly-shoes-beg.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:S, lgtm

#178 Revert "feat(semcov): add metadata"
  js/.changeset/cuddly-shoes-beg.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:S

#179 feat(semcov): add metadata
  js/.changeset/cuddly-shoes-beg.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:S, lgtm

#183 chore(python): fix linting for semconv
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
Labels: size:XS, lgtm

#186 fix(python): parent id for async in langchain-core 0.1.21
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:S, lgtm

#181 fix(python): streaming with_raw_response in openai 1.8.0
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
Labels: size:S, lgtm

#193 fix: set langchain template variables as dict
  python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py
  python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:M, lgtm

#196 fix: metadata spec definition
  spec/semantic_conventions.md
Labels: size:XS, lgtm

#199 feat(llamaindex): scaffold LlamaIndex.TS instrumentor package
  cspell.json
  js/packages/openinference-instrumentation-llama-index/README.md
  js/packages/openinference-instrumentation-llama-index/jest.config.js
  js/packages/openinference-instrumentation-llama-index/package.json
  js/packages/openinference-instrumentation-llama-index/src/index.ts
  js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
  js/packages/openinference-instrumentation-llama-index/tsconfig.esm.json
  js/packages/openinference-instrumentation-llama-index/tsconfig.esnext.json
  js/packages/openinference-instrumentation-llama-index/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:L, lgtm

#201 feat(llama_index)!: support 0.10.0
  cspell.json
  python/examples/llama-index/backend/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/README.rst
  python/instrumentation/openinference-instrumentation-llama-index/examples/chroma_query_engine.py
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/package.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
  python/mypy.ini
Labels: size:M, lgtm

#208 fix: handle BaseException
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:S, lgtm

#211 fix: replace NaN with none in output JSON
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:S, lgtm

#213 fix: retain empty strings for template variables
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:XS, lgtm

#216 fix: avoid openai dependency at import time
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
Labels: size:S, lgtm

#217 fix: missing dependency `typing-extensions`
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
Labels: size:XS, lgtm

#220 fix: missing dependency `typing-extensions`
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
Labels: size:XS, lgtm

#222 fix: avoid langchain dependency at import time
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
Labels: size:S, lgtm

#224 fix: avoid llama-index dependency at import time
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
Labels: size:S, lgtm

#227 docs: Convert READMEs to Markdown
  README.md
  python/instrumentation/openinference-instrumentation-bedrock/README.md
  python/instrumentation/openinference-instrumentation-bedrock/README.rst
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/README.md
  python/instrumentation/openinference-instrumentation-dspy/README.rst
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/README.md
  python/instrumentation/openinference-instrumentation-langchain/README.rst
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/README.md
  python/instrumentation/openinference-instrumentation-llama-index/README.rst
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/README.md
  python/instrumentation/openinference-instrumentation-openai/README.rst
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
Labels: size:L, lgtm

#235 feat: add status description for openai instrumentor
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_stream.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_with_span.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:M, lgtm

#237 feat: add status description to llama-index instrumentor
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
Labels: size:M, lgtm

#238 chore: move projects to stable
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/openinference-semantic-conventions/pyproject.toml
Labels: size:S, lgtm

#245 fix: ensure langchain metadata is always json serializable
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/tox.ini
Labels: size:S, lgtm

#241 fix: allow instrumentation to be suppressed in llama-index instrumentor
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:XS, lgtm
