Repository Arize-ai/openinference, pull requests merged in 2024-05, with the labels that each got.

#414 feat: Create `using_attributes` context managers and have openai instrumentation read from it
  python/openinference-instrumentation/pyproject.toml
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/tests/test_context_managers.py
  python/openinference-instrumentation/tests/test_suppress_tracing.py
Labels: size:L, lgtm

#415 feat: OpenAI instrumentation to capture context attributes
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_async_stream.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_with_span.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:L, lgtm

#417 feat: Add span attributes from OTEL context for llama-index instrumentator
  python/instrumentation/openinference-instrumentation-llama-index/examples/chroma_query_engine.py
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
Labels: size:L, lgtm

#422 refactor: use dict() to pass the context attributes to span
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:S, lgtm

#419 feat: Make langchain instrumentation read context attributes
  python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py
  python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:L, lgtm

#424 fix: require minimum version of openinference-semantic-conventions
  python/openinference-instrumentation/pyproject.toml
Labels: size:XS, lgtm

#420 feat: Make Mistral ai instrumentation read context attributes
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_async.py
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_with_span.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:XL, lgtm

#428 fix: Bump openinference-instrumentation req to avoid yanked release
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
Labels: size:XS, lgtm

#427 fix: Bump openinference-instrumentation req to avoid yanked release
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
Labels: size:XS, lgtm

#426 fix: Bump openinference-instrumentation requirement to avoid yanked release
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
Labels: size:XS, lgtm

#429 fix: Bump openinference-instrumentation req to avoid yanked release
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
Labels: size:XS, lgtm

#421 feat: Make DSPY instrumentation read from attributes from context
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_basic_qa.py
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XL, lgtm

#431 feat: Allow context managers as decorators
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/tests/test_context_managers.py
Labels: size:L, lgtm

#433 feat: Make Bedrock instrumentation read from attributes from context
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_example.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
Labels: size:L, lgtm

#437 feat: Add context manager for prompt template, version, and variables
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/tests/test_context_managers.py
Labels: size:L, lgtm

#438 fix: Add missing context variables to list
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/tests/test_context_managers.py
Labels: size:M, lgtm

#440 test: Add tests to check prompt template context manager
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_async_stream.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:L, lgtm

#441 test: Add tests to check prompt template context manager
  python/instrumentation/openinference-instrumentation-llama-index/examples/chroma_query_engine.py
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
Labels: size:M, lgtm

#442 test: Add tests to check prompt template context manager
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_async.py
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:XXL, lgtm

#443 test: Add tests to check prompt template context manager
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_example.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
Labels: size:M, lgtm

#444 test: Add tests to check prompt template context manager
  python/instrumentation/openinference-instrumentation-dspy/examples/dspy_basic_qa.py
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XL, lgtm

#445 fix: update pdfjs-dist in llama-index-express example
  js/examples/llama-index-express/backend/instrumentation.ts
  js/examples/llama-index-express/frontend/package-lock.json
  js/examples/llama-index-express/frontend/package.json
Labels: size:S, lgtm

#446 feat: Instrumentation reads session id from metadata
  python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py
  python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:XL, lgtm

#448 feat: add support for meta vendor in openinference-instrumentation-bedrock
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
Labels: size:XS, lgtm

#450 fix: update next version in examples
  js/examples/langchain-express/frontend/package-lock.json
  js/examples/langchain-express/frontend/package.json
  js/examples/llama-index-express/frontend/package-lock.json
  js/examples/llama-index-express/frontend/package.json
  js/examples/openai/frontend/package-lock.json
  js/examples/openai/frontend/package.json
Labels: size:S, lgtm

#453 feat(openai-node): add the ability to manually instrument
  js/.changeset/funny-rocks-notice.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
Labels: size:S, lgtm

#455 fix: ensure bazel can discover instrumentation modules in openinference.instrumentations
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
Labels: size:XS, lgtm

#457 refactor: Move `__path__` from top of file
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
Labels: size:S, lgtm

#458 fix: add footnote for how to flatten attributes based on lists of objects
  spec/semantic_conventions.md
Labels: size:L, lgtm

#460 ci: ensure type ignores in langchain tests run across all versions of langchain
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:XS, lgtm

#461 ci: fix llama-index test cases
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/package.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
  python/tox.ini
Labels: size:M, lgtm

#480 fix: improve openai support for non-ascii characters
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
Labels: size:S, lgtm

#479 fix: improve mistral support for non-ascii characters
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_utils.py
Labels: size:S, lgtm

#478 fix: improve dspy support for non-ascii characters
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
Labels: size:S, lgtm

#477 fix: improve llama-index support for non-ascii characters
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:S, lgtm

#476 fix: improve langchain support for non-ascii characters
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:M, lgtm

#475 fix: improve bedrock support for non-ascii characters
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
Labels: size:XS, lgtm

#487 fix: further llama-index support for non-ascii characters
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:S, lgtm

#488 fix: further dspy support for non-ascii characters
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
Labels: size:XS, lgtm

#491 fix(js): fallback patching flag for openAI for immutable modules
  js/.changeset/green-cheetahs-vanish.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
Labels: size:M, lgtm

#489 docs(js): nextjs-13 example
  README.md
  cspell.json
  js/.prettierignore
  js/examples/README.md
  js/examples/nextjs-openai-simple/.env.template
  js/examples/nextjs-openai-simple/.eslintrc.json
  js/examples/nextjs-openai-simple/.gitignore
  js/examples/nextjs-openai-simple/LICENSE
  js/examples/nextjs-openai-simple/README.md
  js/examples/nextjs-openai-simple/instrumentation-node.ts
  js/examples/nextjs-openai-simple/instrumentation.ts
  js/examples/nextjs-openai-simple/next.config.js
  js/examples/nextjs-openai-simple/package-lock.json
  js/examples/nextjs-openai-simple/package.json
  js/examples/nextjs-openai-simple/pages/_app.tsx
  js/examples/nextjs-openai-simple/pages/api/index.ts
  js/examples/nextjs-openai-simple/pages/index.tsx
  js/examples/nextjs-openai-simple/postcss.config.js
  js/examples/nextjs-openai-simple/styles/globals.css
  js/examples/nextjs-openai-simple/tailwind.config.ts
  js/examples/nextjs-openai-simple/tsconfig.json
Labels: size:L, lgtm

#498 feat(js): add semcov resource atters for project name
  js/.changeset/heavy-dryers-happen.md
  js/packages/openinference-semantic-conventions/src/index.ts
  js/packages/openinference-semantic-conventions/src/resource/SemanticResourceAttributes.ts
  js/packages/openinference-semantic-conventions/src/resource/index.ts
Labels: size:S, lgtm

#506 refactor: add token counts to openai streaming examples
  python/instrumentation/openinference-instrumentation-openai/README.md
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_async_stream.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_async_stream_with_raw_response.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_stream.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_stream_with_raw_response.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_function_calling.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_raw_response.py
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_with_streaming_response.py
  python/instrumentation/openinference-instrumentation-openai/examples/embeddings.py
  python/instrumentation/openinference-instrumentation-openai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-openai/examples/with_httpx_instrumentor.py
Labels: size:M, lgtm

#505 refactor: fix tests for mistralai v0.1
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
Labels: size:XS, lgtm

#497 feat(llamaindex.TS): llama-index-ts initial package creation
  cspell.json
  js/package.json
  js/packages/openinference-instrumentation-langchain/jest.config.js
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-llama-index/examples/instrumentation.ts
  js/packages/openinference-instrumentation-llama-index/examples/llamaindex-node.ts
  js/packages/openinference-instrumentation-llama-index/jest.config.js
  js/packages/openinference-instrumentation-llama-index/package.json
  js/packages/openinference-instrumentation-llama-index/src/index.ts
  js/packages/openinference-instrumentation-llama-index/src/instrumentation.ts
  js/packages/openinference-instrumentation-llama-index/test/llamaIndex.test.ts
  js/packages/openinference-instrumentation-openai/package.json
  js/pnpm-lock.yaml
Labels: size:L, lgtm

#504 refactor: fix tests for llama-index latest
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
Labels: size:M, lgtm

#508 fix: remove unnecessary `MistralClient` instantiation
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:S, lgtm

#511 fix: tests for langchain latest @ 2.1
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:S, lgtm

#510 docs: minimum working example of a custom retriever
  python/instrumentation/openinference-instrumentation-langchain/examples/custom_retriever.py
  python/instrumentation/openinference-instrumentation-langchain/examples/pathway_retriever.py
Labels: size:M, lgtm

#513 chore: fix langchain tests for python 12
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:M, lgtm
