Repository Arize-ai/openinference, pull requests merged in 2024-06, with the labels that each got.

#515 fix: `GetResponseEndEvent` payload removal
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:XS, lgtm

#517 fix: make tracer a singleton instance
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:XL, lgtm

#520 fix: handle ToolMessage in LangChain instrumentor
  python/instrumentation/openinference-instrumentation-langchain/examples/chain_metadata.py
  python/instrumentation/openinference-instrumentation-langchain/examples/custom_retriever.py
  python/instrumentation/openinference-instrumentation-langchain/examples/exchange_rate_tool.py
  python/instrumentation/openinference-instrumentation-langchain/examples/openai_chat_stream.py
  python/instrumentation/openinference-instrumentation-langchain/examples/pathway_retriever.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:M, lgtm

#527 chore: fix version typo in llama-index README
  python/instrumentation/openinference-instrumentation-llama-index/README.md
Labels: size:XS, lgtm

#528 chore: update requirements for llama-index examples
  python/instrumentation/openinference-instrumentation-llama-index/examples/ingestion_pipeline.py
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
Labels: size:M, lgtm

#529 chore: update llama-index docker example
  python/examples/llama-index/backend/poetry.lock
  python/examples/llama-index/backend/pyproject.toml
Labels: size:S, lgtm

#534 fix(langchain): message parsing for langgraph
  python/instrumentation/openinference-instrumentation-langchain/examples/langgraph_agent_supervisor.py
  python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:L, lgtm

#535 feat: Add vision semantic conventions messages
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/semantic_conventions.md
Labels: size:L, lgtm

#543 feat: Add multimodal semantic convention for llm message contents
  js/.changeset/young-cobras-confess.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:M, lgtm

#540 feat: Add guardrails span kind
  js/.changeset/hip-trees-whisper.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/traces.md
Labels: size:S, lgtm

#548 feat(semcov): guardrail span kind for python
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
Labels: size:S

#550 feat: guardail js span kind
  js/.changeset/quick-cougars-raise.md
Labels: size:XS

#551 feat(semcov): js span_kind for guardrail
  js/.changeset/cuddly-apricots-float.md
Labels: size:XS

#554 feat: add evaluator span kind to semantic conventions
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  spec/traces.md
Labels: size:XS, lgtm

#542 feat: Add multimodal content arrays to llm messages
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_multimodal.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:L, lgtm
