Repository Arize-ai/openinference, pull requests merged in 2024-09, with the labels that each got.

#996 chore(anthropic): dynamically import anthropic
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/__init__.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
Labels: size:S, lgtm

#998 fix(anthropic): dynamically import anthropic
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
Labels: size:XS, lgtm

#1001 fix: remove setting the global logger level
  python/openinference-instrumentation/src/openinference/instrumentation/logging.py
Labels: size:XS, lgtm

#997 fix(llama-index): ensure llamaindex response models are serializable
  python/instrumentation/openinference-instrumentation-llama-index/examples/neutrino_query_engine.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:M, lgtm

#947 feat(mistralai)!: support v1
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions.py
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_async.py
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_async_streaming.py
  python/instrumentation/openinference-instrumentation-mistralai/examples/chat_completions_streaming.py
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/__init__.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_chat_wrapper.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_stream.py
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/cassettes/test_instrumentor/test_asynchronous_streaming_chat_completions_emits_expected_span[False].yaml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/cassettes/test_instrumentor/test_asynchronous_streaming_chat_completions_emits_expected_span[True].yaml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/cassettes/test_instrumentor/test_synchronous_streaming_chat_completions_emits_expected_span[False].yaml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/cassettes/test_instrumentor/test_synchronous_streaming_chat_completions_emits_expected_span[True].yaml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/cassettes/test_instrumentor/test_synchronous_streaming_chat_completions_with_tool_call_response_emits_expected_spans[False].yaml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/cassettes/test_instrumentor/test_synchronous_streaming_chat_completions_with_tool_call_response_emits_expected_spans[True].yaml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
  python/tox.ini
Labels: size:XXL, lgtm

#1004 fix: Don't check length when converting ToolMetadata to OpenAI format
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:XS, lgtm

#1010 feat: id generator with separate source of randomness
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/test_id_generator.py
Labels: size:M, lgtm

#1012 fix: increase version lower bound for openinference-instrumentation
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
Labels: size:S, lgtm

#1026 fix: add missing dependency opentelemetry-sdk
  python/openinference-instrumentation/pyproject.toml
Labels: size:XS, lgtm

#1031 chore(openai-node): add manual instrumentation example
  js/packages/openinference-instrumentation-openai/examples/chat.ts
  js/packages/openinference-instrumentation-openai/examples/instrumentation.ts
  js/packages/openinference-instrumentation-openai/examples/manual-instrumentation.ts
  js/packages/openinference-instrumentation-openai/package.json
  js/pnpm-lock.yaml
Labels: size:L, lgtm

#1032 fix(examples): bump langchain js express example dependencies
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/backend/package.json
Labels: size:XS, lgtm

#1029 ci(llama-index): remove failing checks in tests because they're not important
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_callback.py
Labels: size:S, lgtm

#1035 ci: remove instructor latest in tox
  python/tox.ini
Labels: size:XS, lgtm

#1036 chore: remove example lock files
  js/examples/langchain-express/backend/package-lock.json
  js/examples/langchain-express/frontend/package-lock.json
  js/examples/llama-index-express/backend/package-lock.json
  js/examples/llama-index-express/frontend/package-lock.json
  js/examples/next-openai-telemetry-app/package-lock.json
  js/examples/nextjs-openai-simple/package-lock.json
  js/examples/openai/backend/package-lock.json
  js/examples/openai/frontend/package-lock.json
Labels: size:XS

#1037 fix: remove more lock files
  python/examples/llama-index/frontend/package-lock.json
Labels: size:XS

#1040 ci: exclude voletile libraries from CI
  python/tox.ini
Labels: size:S, lgtm

#1044 ci: update imports so liteLLM tests pass
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
  python/tox.ini
Labels: size:S, lgtm

#1045 feat: support langchain 0.3
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/tests/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/tests/_helpers.py
  python/instrumentation/openinference-instrumentation-langchain/tests/conftest.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
  python/tox.ini
Labels: size:L, lgtm
