Repository Arize-ai/openinference, pull requests merged in 2024-07, with the labels that each got.

#570 ci: pnpm action v4
  .github/workflows/typescript-CI.yaml
Labels: size:XS

#569 fix(js): fix spelling in conventions
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:XS, lgtm

#572 ci: Update typescript-publish.yaml
  .github/workflows/typescript-publish.yaml
Labels: size:XS

#576 chore: fix test for dspy
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:M, lgtm

#577 chore: update tooling
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
Labels: size:M, lgtm

#578 feat: helper function to `get_current_span()` for langchain
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/openinference/instrumentation/langchain/test_instrumentor.py
Labels: size:M, lgtm

#575 feat: Add vision instrumentation
  python/instrumentation/openinference-instrumentation-llama-index/examples/multimodal_stream_chat.py
  python/instrumentation/openinference-instrumentation-llama-index/examples/multimodal_stream_completion.py
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_multimodal.py
Labels: size:XL, lgtm

#553 feat(guardrailsai): add instrumentation support
  python/instrumentation/openinference-instrumentation-guardrails/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-guardrails/LICENSE
  python/instrumentation/openinference-instrumentation-guardrails/README.md
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/__init__.py
  python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/_wrap_guard_call.py
  python/instrumentation/openinference-instrumentation-guardrails/src/openinference/instrumentation/guardrails/version.py
  python/instrumentation/openinference-instrumentation-guardrails/tests/openinference/instrumentation/guardrails/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#584 chore: fix readme format
  js/examples/README.md
Labels: size:XS

#586 feat(guardrailsai): add README and release please for guardrails
  README.md
  release-please-config.json
Labels: size:XS, lgtm

#590 chore: add symlinks for editable installs
  python/openinference-instrumentation/src/openinference/instrumentation/guardrails
Labels: size:XS, lgtm

#591 fix(openai): missing span when stream response is used as context manager
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_stream.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:M, lgtm

#596 chore: fix guardrails CI
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/tests/openinference/instrumentation/guardrails/test_instrumentor.py
Labels: size:M, lgtm

#593 fix(langchain): missing partial variables for chat prompt template
  python/instrumentation/openinference-instrumentation-langchain/examples/chat_prompt_template.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/conftest.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_get_cls_name.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_prompt_template.py
Labels: size:L, lgtm

#599 chore: Update requirements.txt for examples
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
Labels: size:XS, lgtm

#588 feat: VertexAI instrumentor
  README.md
  python/instrumentation/openinference-instrumentation-vertexai/LICENSE
  python/instrumentation/openinference-instrumentation-vertexai/README.md
  python/instrumentation/openinference-instrumentation-vertexai/examples/audio_transcription.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/audio_understanding.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/automatic_function_calling.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/basic_generation.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/chat.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/document_understanding.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/function_calling.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/gapic.async_client.generate_content.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/gapic.async_client.stream_generate_content.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/gapic.client.generate_content.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/gapic.client.stream_generate_content.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/get_text_embeddings.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/image_from_cloud_storage.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/image_upload.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-vertexai/examples/system_instructions.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/vertexai.model.count_tokens.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/vertexai.model.count_tokens_async.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/vertexai.model.generate_content.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/vertexai.model.generate_content.stream.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/vertexai.model.generate_content_async.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/vertexai.model.generate_content_async.stream.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/video_and_audio_understanding.py
  python/instrumentation/openinference-instrumentation-vertexai/examples/video_understanding.py
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/__init__.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_accumulator.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_instrumentation_status.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_proxy.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_wrapper.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/package.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/py.typed
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/version.py
  python/instrumentation/openinference-instrumentation-vertexai/tests/conftest.py
  python/instrumentation/openinference-instrumentation-vertexai/tests/test_gapic_client.py
  python/instrumentation/openinference-instrumentation-vertexai/tests/test_proxy.py
  python/tox.ini
  release-please-config.json
Labels: size:XXL, lgtm

#601 chore: fix typo in README
  README.md
Labels: size:XS, lgtm

#602 chore: add symlink for vertexai editable install
  python/openinference-instrumentation/src/openinference/instrumentation/vertexai
Labels: size:XS, lgtm

#605 docs: Update README.md
  python/instrumentation/openinference-instrumentation-guardrails/README.md
Labels: size:S, lgtm

#585 feat(bedrock): add converse api support for bedrock
  python/instrumentation/openinference-instrumentation-bedrock/README.md
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_example.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_instrumentor.py
Labels: size:XL, lgtm

#623 fix(js): fix lowercase values in semantic conventions
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: size:M, lgtm

#624 ci: setup codeowners
  .github/CODEOWNERS
Labels: size:XS

#603 chore: update js deps
  js/package.json
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-llama-index/package.json
  js/packages/openinference-instrumentation-openai/package.json
  js/pnpm-lock.yaml
Labels: size:M, lgtm

#625 fix: include token counts from langchain ChatAnthropic model
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
  python/tox.ini
Labels: size:M, lgtm

#628 fix: allow `raw` to be dict or object for llama-index v0.10.58
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
Labels: size:S, lgtm

#630 chore: clean helper function in langchain instrumentation
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:XS, lgtm

#639 feat: Add TracingConfig for configuration settings in instrumentations
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/src/openinference/instrumentation/context_attributes.py
  python/openinference-instrumentation/src/openinference/instrumentation/helpers.py
  python/openinference-instrumentation/src/openinference/instrumentation/logging.py
  python/openinference-instrumentation/tests/test_config.py
  spec/README.md
  spec/configuration.md
Labels: size:XXL, lgtm

#640 feat: Add TraceConfig handling
  python/instrumentation/openinference-instrumentation-openai/examples/chat_completions_multimodal_with_config.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/__init__.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:XXL, lgtm

#648 fix: Fix configuraiton table
  spec/configuration.md
Labels: size:S, lgtm

#649 fix: Fix configuraiton table
  spec/configuration.md
Labels: size:XS

#645 feat(langchain): capture image in chat message
  python/instrumentation/openinference-instrumentation-langchain/examples/image_openai.py
  python/instrumentation/openinference-instrumentation-langchain/examples/image_vertexai.py
  python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_image_in_message.py
Labels: size:L, lgtm

#656 feat(openinference-core): js support for sessions
  js/packages/openinference-core/jest.config.js
  js/packages/openinference-core/package.json
  js/packages/openinference-core/src/trace/session.ts
  js/packages/openinference-core/test/session.test.ts
  js/packages/openinference-core/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:M

#659 docs: Update pull_request_template.md
  python/pull_request_template.md
Labels: size:XS

#644 feat(haystack): add instrumentation support
  python/instrumentation/openinference-instrumentation-haystack/LICENSE
  python/instrumentation/openinference-instrumentation-haystack/README.md
  python/instrumentation/openinference-instrumentation-haystack/examples/qa_rag_pipeline.py
  python/instrumentation/openinference-instrumentation-haystack/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/version.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#622 feat(crewAI): instrumentation
  python/instrumentation/openinference-instrumentation-crewai/LICENSE
  python/instrumentation/openinference-instrumentation-crewai/README.md
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/__init__.py
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/version.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#662 feat(crewai): release crewAI to pypi
  README.md
  release-please-config.json
Labels: size:XS, lgtm

#653 feat: Add config handling to instrumentation
  python/instrumentation/openinference-instrumentation-llama-index/examples/multimodal_stream_chat_with_config.py
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_multimodal.py
Labels: size:XL, lgtm

#663 feat(haystack): add README and release please for haystack
  README.md
  release-please-config.json
Labels: size:S, lgtm

#672 refactor(openinfernce-core): unify under context attrs
  js/packages/openinference-core/jest.config.js
  js/packages/openinference-core/package.json
  js/packages/openinference-core/src/index.ts
  js/packages/openinference-core/src/trace/contextAttributes.ts
  js/packages/openinference-core/src/trace/index.ts
  js/packages/openinference-core/src/trace/session.ts
  js/packages/openinference-core/test/trace/contextAttributes.test.ts
  js/packages/openinference-core/tsconfig.json
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  js/pnpm-lock.yaml
Labels: size:L

#674 feat(openinference-core): getAttribuesFromContext
  js/packages/openinference-core/src/trace/contextAttributes.ts
Labels: size:M

#641 feat(liteLLM): instrumentation
  python/instrumentation/openinference-instrumentation-litellm/.gitignore
  python/instrumentation/openinference-instrumentation-litellm/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-litellm/LICENSE
  python/instrumentation/openinference-instrumentation-litellm/README.md
  python/instrumentation/openinference-instrumentation-litellm/guides/client_demo.ipynb
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/package.py
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/py.typed
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/version.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
Labels: size:XXL, lgtm

#675 chore: add composability tests
  js/packages/openinference-core/src/trace/contextAttributes.ts
  js/packages/openinference-core/test/trace/contextAttributes.test.ts
Labels: size:M, lgtm

#676 feat(litellm): add README and release please for liteLLM
  README.md
  release-please-config.json
Labels: size:XS, lgtm

#673 feat: Config settings concentrated in common instrumentation package
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/tox.ini
Labels: size:L, lgtm

#682 fix: Ensure string type to check URLs
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
Labels: size:XS, lgtm

#679 feat: Move attribute censorship based on config to common instrumentation
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/__init__.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler_config.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/__init__.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:L, lgtm
