Repository Arize-ai/openinference, pull requests merged in 2025-02, with the labels that each got.

#1246 feat(liteLLM): add support for acompletion streaming (resolves #1224)
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
Labels: size:M

#1249 fix(dspy): dspy 2.6.0 upgrade
  python/instrumentation/openinference-instrumentation-dspy/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/package.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
  python/mypy.ini
Labels: size:M

#1257 ci: remove httpx restriction
  python/tox.ini
Labels: size:S

#1255 ci: use paths-filter in py and js CI
  .github/workflows/python-CI.yaml
  .github/workflows/typescript-CI.yaml
Labels: size:L

#1238 fix(smolagents): support smolagents nested llm input message contents
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_openai_server_model_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_openai_server_model_with_tool_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:M

#1259 ci: parallelize tox testenv for python canary cron
  .github/workflows/python-cron.yaml
Labels: size:L

#1260 ci: fix type check for mistralai
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/tests/openinference/instrumentation/mistralai/test_instrumentor.py
Labels: size:XS

#1261 ci: combine all Python releases into single PR
  .github/workflows/release.yml
  release-please-config.json
Labels: size:M

#1263 fix: support python 3.13 and drop python 3.8
  .github/workflows/python-CI.yaml
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-anthropic/test-requirements.txt
  python/instrumentation/openinference-instrumentation-autogen/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/test-requirements.txt
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
  python/openinference-instrumentation/pyproject.toml
  python/openinference-semantic-conventions/pyproject.toml
  python/tox.ini
Labels: size:M

#1265 ci: fix test cassette for haystack
  .github/workflows/python-CI.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_cohere_reranker_span_has_expected_attributes.yaml
Labels: size:XS

#1269 fix: use safe_json_dumps for invocation parameters in litellm instrumentor
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
Labels: size:XS

#1266 ci: notify slack if pypi publication fails
  .github/workflows/python-cron.yaml
  .github/workflows/release.yml
Labels: size:M

#1271 fix: remove mistralai dependency in mistralai instrumentor
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/src/openinference/instrumentation/mistralai/_stream.py
  python/instrumentation/openinference-instrumentation-mistralai/test-requirements.txt
  python/tox.ini
Labels: size:S

#1274 fix(smolagents): support new managed agents
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Labels: size:S

#1276 feat(smolagents): add entrypoint for use in opentelemetry-instrument
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
Labels: size:XS

#1282 fix: fix test failures with crew-latest
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session_context_attributes.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
  python/tox.ini
Labels: size:S

#1277 feat(smolagents): updates to latest and makes examples use opentelemetry-instrument
  python/.gitignore
  python/instrumentation/openinference-instrumentation-smolagents/README.md
  python/instrumentation/openinference-instrumentation-smolagents/examples/README.md
  python/instrumentation/openinference-instrumentation-smolagents/examples/e2b_example.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/env.example
  python/instrumentation/openinference-instrumentation-smolagents/examples/managed_agent.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/openai_model.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/openai_model_tool_call.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/rag.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-smolagents/examples/text2sql.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/tool_calling_agent.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/tool_invocation.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:L

#1288 fix(llama-index): fix typo in llama-index entry point
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_instrumentor.py
Labels: size:XS

#1294 feat(smolagents): support smolagents on python 3.13
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
Labels: size:XS

#1290 feat: define openinference_instrumentor entry points for all libraries
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-autogen/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
Labels: size:M

#1299 fix(llama-index): Capture tool call id from additional_kwargs
  python/instrumentation/openinference-instrumentation-llama-index/examples/multi_tool_calling.py
  python/instrumentation/openinference-instrumentation-llama-index/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:M

#1300 fix(js): update dependancies for security
  js/package.json
  js/pnpm-lock.yaml
Labels: size:XS

#1295 fix(haystack): update haystack for compatibility with 2.10
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:L

#1311 ci: fix type check on unit tests for llama-index
  .github/workflows/python-CI.yaml
  .github/workflows/python-cron.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_handler.py
Labels: size:S

#1312 ci: fix type check on unit tests for anthropic
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:S

#1313 ci: fix type check for bedrock anthropic
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/_messages.py
Labels: size:S

#1315 fix: allow user override of id generator
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/test_id_generator.py
Labels: size:S
