Repository Arize-ai/openinference, pull requests merged in 2025-07, with the labels that each got.

#1822 fix: small typo in str() call
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:XS

#1789 feat: openinference-instrumentation-openllmetry (openllmetry converter)
  .release-please-manifest.json
  pyproject.toml
  python/instrumentation/openinference-instrumentation-openllmetry/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-openllmetry/LICENSE
  python/instrumentation/openinference-instrumentation-openllmetry/README.md
  python/instrumentation/openinference-instrumentation-openllmetry/examples/langchain-example.py
  python/instrumentation/openinference-instrumentation-openllmetry/examples/openai-toolcalling-example.py
  python/instrumentation/openinference-instrumentation-openllmetry/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-openllmetry/pyproject.toml
  python/instrumentation/openinference-instrumentation-openllmetry/src/openinference/instrumentation/openllmetry/__init__.py
  python/instrumentation/openinference-instrumentation-openllmetry/src/openinference/instrumentation/openllmetry/_span_processor.py
  python/instrumentation/openinference-instrumentation-openllmetry/src/openinference/instrumentation/openllmetry/version.py
  python/instrumentation/openinference-instrumentation-openllmetry/tests/openinference/instrumentation/openllmetry/cassettes/test_instrumentor/TestOpenLLMetryInstrumentor.test_openllmetry_instrumentor.yaml
  python/instrumentation/openinference-instrumentation-openllmetry/tests/openinference/instrumentation/openllmetry/test_instrumentor.py
  python/scripts/select_tox_environments.py
  python/tox.ini
  release-please-config.json
  requirements.txt
Labels: size:XXL

#1825 ci: add timeout for python CI jobs
  .github/workflows/python-CI.yaml
  .github/workflows/python-cron.yaml
Labels: size:XS, lgtm

#1792 feat!: set openinference processor as the exclusive processor by default
  python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/__init__.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/package.py
  python/instrumentation/openinference-instrumentation-openai-agents/test-requirements.txt
  python/instrumentation/openinference-instrumentation-openai-agents/tests/test_span_attribute_helpers.py
Labels: size:S

#1791 feat: add llm.provider and llm.system attributes to langchain instrumentation
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/langchain_provider_map.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_config.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_image_in_message.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:L

#1841 fix(openinference-vercel): Bump package ranges
  js/.changeset/shiny-clouds-join.md
  js/packages/openinference-vercel/package.json
  js/pnpm-lock.yaml
Labels: size:S

#1845 feat(smolagents): Improve Display Of Handled Errors
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Labels: size:S

#1857 fix(vercel): span processor should not override existing span kind
  .github/workflows/typescript-CI.yaml
  js/.changeset/hot-terms-hide.md
  js/examples/langchain-express/frontend/app/globals.css
  js/examples/llama-index-express/frontend/app/globals.css
  js/examples/next-openai-telemetry-app/app/globals.css
  js/examples/openai/frontend/app/globals.css
  js/package.json
  js/packages/openinference-vercel/src/utils.ts
  js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
  js/pnpm-lock.yaml
Labels: size:M

#1863 feat: Allow to hide llm.prompts span from trace config
  js/packages/openinference-core/src/trace/trace-config/constants.ts
  js/packages/openinference-core/src/trace/trace-config/index.ts
  js/packages/openinference-core/src/trace/trace-config/maskingRules.ts
  js/packages/openinference-core/src/trace/trace-config/types.ts
  js/packages/openinference-core/test/trace-config/maskingRules.test.ts
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/test_config.py
  spec/configuration.md
Labels: size:M, lgtm

#1817 feat(langchain4j): Java Openinference client, langchain4j example
  .github/workflows/java-publish.yml
  .gitignore
  .release-please-manifest.json
  README.md
  java/.gitignore
  java/README.md
  java/build.gradle
  java/examples/langchain4j-example/README.md
  java/examples/langchain4j-example/build.gradle
  java/examples/langchain4j-example/src/main/java/io/openinference/examples/LangChain4jExample.java
  java/gradle.properties
  java/gradle/wrapper/gradle-wrapper.jar
  java/gradle/wrapper/gradle-wrapper.properties
  java/gradlew
  java/gradlew.bat
  java/instrumentation/openinference-instrumentation-langchain4j/build.gradle
  java/instrumentation/openinference-instrumentation-langchain4j/src/main/java/com/arize/instrumentation/langchain4j/LangChain4jInstrumentor.java
  java/instrumentation/openinference-instrumentation-langchain4j/src/main/java/com/arize/instrumentation/langchain4j/LangChain4jModelListener.java
  java/openinference-instrumentation/build.gradle
  java/openinference-instrumentation/src/main/java/com/arize/instrumentation/OITracer.java
  java/openinference-instrumentation/src/main/java/com/arize/instrumentation/TraceConfig.java
  java/openinference-semantic-conventions/build.gradle
  java/openinference-semantic-conventions/src/main/java/com/arize/semconv/trace/SemanticConventions.java
  java/openinference-semantic-conventions/src/main/java/com/arize/semconv/trace/SemanticResourceAttributes.java
  java/settings.gradle
  release-please-config.json
Labels: size:XXL

#1875 fix: bump java, add release-please gradle property
  java/build.gradle
  java/instrumentation/openinference-instrumentation-langchain4j/gradle.properties
  java/openinference-instrumentation/gradle.properties
  java/openinference-semantic-conventions/gradle.properties
  release-please-config.json
Labels: size:M

#1794 feat(crewai): capture graph.node.id and graph.node.parent_id semantics
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
Labels: size:M

#1880 feat: java and python release
  .github/workflows/java-publish.yml
  .github/workflows/release.yml
Labels: size:L

#1881 feat: Java release only, please
  java/openinference-semantic-conventions/build.gradle
Labels: size:XS

#1884 fix: typo on release
  java/openinference-semantic-conventions/build.gradle
  release-please-config.json
Labels: size:S

#1885 fix: json error, release please
  release-please-config.json
Labels: size:XS

#1878 fix: fix IndexError for empty function output
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
  python/instrumentation/openinference-instrumentation-openai-agents/tests/test_span_attribute_helpers.py
Labels: size:S, lgtm

#1873 feat: add support for non global trace provider in instrumentations
  js/.changeset/empty-pianos-stay.md
  js/packages/openinference-instrumentation-beeai/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV2.test.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
Labels: size:XL

#1894 docs: add maven central badges to the readmes
  README.md
Labels: size:S

#1901 feat(java): add tool calling instrumentation, prepare dependabot PR
  .github/dependabot.yml
  java/examples/langchain4j-example/src/main/java/io/openinference/examples/LangChain4jExample.java
  java/instrumentation/openinference-instrumentation-langchain4j/gradle.properties
  java/instrumentation/openinference-instrumentation-langchain4j/src/main/java/com/arize/instrumentation/langchain4j/LangChain4jModelListener.java
  java/openinference-semantic-conventions/gradle.properties
  java/openinference-semantic-conventions/src/main/java/com/arize/semconv/trace/SemanticConventions.java
  scripts/generate_dependabot.py
Labels: size:L

#1904 feat: add dependabot github action
  .github/dependabot.yml
  .github/workflows/dependabot-update.yml
  java/openinference-instrumentation/gradle.properties
  scripts/generate_dependabot.py
Labels: size:L

#1977 fix: dependabot only security updates
  .github/dependabot.yml
  scripts/generate_dependabot.py
Labels: size:L

#1979 fix: download instrumentor from maven central
  java/examples/langchain4j-example/build.gradle
Labels: size:XS

#1980 docs: Fix spec batch link in README
  README.md
Labels: size:XS

#1836 feat: enhance function call span attributes with input value and erro…
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
Labels: size:M

#1867 feat(autogen-agentchat): capture graph.node.id and graph.node.parent_id semantics
  python/instrumentation/openinference-instrumentation-autogen-agentchat/pyproject.toml
  python/instrumentation/openinference-instrumentation-autogen-agentchat/src/openinference/instrumentation/autogen_agentchat/_wrappers.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/tests/test_instrumenting_team.py
Labels: size:M, lgtm

#1990 fix(dspy): mask api keys passed as arguments
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XS

#1993 feat: unwrap input output keys from io values
  python/instrumentation/openinference-instrumentation-langchain/examples/runnable_sequence_with_pydantic_model.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_convert_io.py
Labels: size:XXL, lgtm

#1995 fix: tool call for anthropic bedrock invoke model
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:S, lgtm

#2008 docs: add instrumentation base modules to top level readme
  README.md
Labels: size:M

#2013 feat(python): get_first_span_id via a context manager
  python/openinference-instrumentation/src/openinference/instrumentation/_capture.py
  python/openinference-instrumentation/tests/test_context_managers.py
Labels: size:S

#2012 feat: Instrument sssistant tool calls made by LangGraph
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_langgraph_tool_calls.py
Labels: size:L, lgtm

#2004 fix: openai-agents CI add eval_type_backport dependency for Python <3.10 compatibility
  python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
Labels: size:XS
