Repository Arize-ai/openinference, pull requests merged in 2025-08, with the labels that each got.

#2023 fix(llama-index): handle BaseAgent import changes in v0.13.0+
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:M

#2033 fix: serialization of response schema in invocation parameters for google-adk
  python/instrumentation/openinference-instrumentation-google-adk/src/openinference/instrumentation/google_adk/_wrappers.py
Labels: size:XS, lgtm

#2041 docs: add springai
  README.md
Labels: size:XS

#2044 feat: Upgrade workflow java 17
  .github/workflows/release.yml
  java/instrumentation/openinference-instrumentation-langchain4j/gradle.properties
  java/instrumentation/openinference-instrumentation-springAI/gradle.properties
  java/openinference-instrumentation/gradle.properties
  java/openinference-semantic-conventions/gradle.properties
Labels: size:S

#2039 feat(js-bedrock): Add ReadME and custom tracing provider
  js/.changeset/full-bears-hang.md
  js/packages/openinference-instrumentation-bedrock/README.md
  js/packages/openinference-instrumentation-bedrock/src/instrumentation.ts
  js/packages/openinference-instrumentation-bedrock/test/helpers/vcr-helpers.ts
  js/packages/openinference-instrumentation-bedrock/test/instrumentation.test.ts
  js/packages/openinference-instrumentation-bedrock/test/recordings/should-use-the-provided-tracer-provider-instead-of-the-global-one-constructor.json
  js/packages/openinference-instrumentation-bedrock/test/recordings/should-use-the-provided-tracer-provider-instead-of-the-global-one-registerinstrumentations.json
  js/packages/openinference-instrumentation-bedrock/test/recordings/should-use-the-provided-tracer-provider-instead-of-the-global-one-settracerprovider.json
Labels: size:XXL

#2049 feat: add springAI build target
  java/build.gradle
Labels: size:XS

#2052 chore: pin form-data version
  js/examples/nextjs-openai-simple/package-lock.json
  js/package.json
  js/pnpm-lock.yaml
  python/examples/llama-index/frontend/package-lock.json
  python/examples/llama-index/frontend/package.json
Labels: size:XS

#2061 fix: trigger springAI release
  .github/workflows/release.yml
  java/instrumentation/openinference-instrumentation-springAI/build.gradle
Labels: size:S

#1874 feat(js-bedrock-agent-runtime): AWS Bedrock Agent Instumentaion for JS
  js/.changeset/weak-ears-serve.md
  js/packages/openinference-instrumentation-bedrock-agent-runtime/examples/.env.example
  js/packages/openinference-instrumentation-bedrock-agent-runtime/examples/agent-instrumentation.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/examples/run-invoke-agent.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/jest.config.js
  js/packages/openinference-instrumentation-bedrock-agent-runtime/package.json
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/request-attributes.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/callback-handler.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/index.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/instrumentation.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/stream-utils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/custom-provider.test.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/integration.instrumentation.agent-without-traces.test.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-custom-trace-provider-bedrockagentinstrumentation-with-a-custom-tracer-prov_1528379976/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-custom-trace-provider-unnamed-test_3593248847/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-without-traces-bedrockagentinstrumentation-integration-agent-attributes-and_3073832749/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/utils/polly.config.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/utils/test-utils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/tsconfig.esm.json
  js/packages/openinference-instrumentation-bedrock-agent-runtime/tsconfig.esnext.json
  js/packages/openinference-instrumentation-bedrock-agent-runtime/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XXL

#2060 feat: BeeAI Framework Updates
  python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/_utils.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/chat.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/tool.py
Labels: size:M

#2053 feat(Agno): Capture graph attributes for agent visual
  python/instrumentation/openinference-instrumentation-agno/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-agno/pyproject.toml
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
  python/instrumentation/openinference-instrumentation-agno/tests/openinference/instrumentation/agno/fixtures/team_coordinate_run.yaml
  python/instrumentation/openinference-instrumentation-agno/tests/test_instrumentor.py
Labels: size:XXL, lgtm

#2089 Revert "feat(Agno): Capture graph attributes for agent visual"
  python/instrumentation/openinference-instrumentation-agno/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-agno/pyproject.toml
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
  python/instrumentation/openinference-instrumentation-agno/tests/openinference/instrumentation/agno/fixtures/team_coordinate_run.yaml
  python/instrumentation/openinference-instrumentation-agno/tests/test_instrumentor.py
Labels: size:XXL

#2091 feat(anthropic): Added support for anthropic sdk input images rendering
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_image_input_messages.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_image_input_messages_with_stream.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:XL

#2074 feat(bedrock-agent-runtime): Js bedrock agent instrumentation trace tree Building
  js/.changeset/few-zebras-sing.md
  js/packages/openinference-core/src/utils/index.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/README.md
  js/packages/openinference-instrumentation-bedrock-agent-runtime/examples/run-invoke-agent.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/jest.config.js
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/attributeExtractionUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/attributeUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/constants.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/requestAttributes.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/types.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/callbackHandler.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/collector/agentChunkSpan.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/collector/agentTraceAggregator.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/collector/agentTraceNode.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/collector/traceNodeStack.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/instrumentation.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/spanCreator.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/streamUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/types.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/utils/jsonUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/utils/typeUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/integration.instrumentation.agent-traces.test.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-with-traces-bedrockagentinstrumentation-trace-collector-integration-agent-a_1614381117/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-with-traces-bedrockagentinstrumentation-trace-collector-integration-agent-a_3264752613/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-with-traces-bedrockagentinstrumentation-trace-collector-integration-agent-a_3453170410/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-with-traces-bedrockagentinstrumentation-trace-collector-integration-agent-a_3722574698/recording.har
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-with-traces-bedrockagentinstrumentation-trace-collector-integration-agent-at_817711251/recording.har
  js/packages/openinference-instrumentation-openai/README.md
Labels: size:XXL

#2087 fix(smolagents): use new token_usage structure
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Labels: size:S

#2106 fix: SpringAI multiple output messages
  java/examples/spring-ai-example/src/main/java/com/arize/openinference/examples/SpringAI.java
  java/instrumentation/openinference-instrumentation-springAI/build.gradle
  java/instrumentation/openinference-instrumentation-springAI/src/main/java/com/arize/instrumentation/springAI/SpringAIInstrumentor.java
Labels: size:S

#2021 feat: Openlit span processor
  .gitignore
  python/instrumentation/openinference-instrumentation-openlit/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-openlit/LICENSE
  python/instrumentation/openinference-instrumentation-openlit/README.md
  python/instrumentation/openinference-instrumentation-openlit/examples/joke.py
  python/instrumentation/openinference-instrumentation-openlit/examples/langchain_example.py
  python/instrumentation/openinference-instrumentation-openlit/examples/openai_toolcalling_example.py
  python/instrumentation/openinference-instrumentation-openlit/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-openlit/pyproject.toml
  python/instrumentation/openinference-instrumentation-openlit/src/openinference/instrumentation/openlit/__init__.py
  python/instrumentation/openinference-instrumentation-openlit/src/openinference/instrumentation/openlit/_span_processor.py
  python/instrumentation/openinference-instrumentation-openlit/src/openinference/instrumentation/openlit/py.typed
  python/instrumentation/openinference-instrumentation-openlit/src/openinference/instrumentation/openlit/version.py
  python/instrumentation/openinference-instrumentation-openlit/tests/openinference/instrumentation/openlit/cassettes/test_instrumentor/TestOpenLitInstrumentor.test_openlit_instrumentor.yaml
  python/instrumentation/openinference-instrumentation-openlit/tests/openinference/instrumentation/openlit/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-openllmetry/examples/langchain_example.py
  python/instrumentation/openinference-instrumentation-openllmetry/examples/openai_toolcalling_example.py
  python/tox.ini
Labels: size:XXL

#2058 feat(bedrock): Add instrumentation for guardrailTrace
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_attribute_extractor.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_trace_collector.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_guardrail_intervention.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_streaming_with_guardrails.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/test_invoke_agent_instrumentor.py
Labels: size:XL

#2118 fix(smolagents): prevent duplicate llm spans
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:M, lgtm

#2120 feat: Openlit span processor
  python/instrumentation/openinference-instrumentation-openlit/README.md
Labels: size:XS

#2128 docs: Add instrumentation for smolagents to README
  README.md
Labels: size:XS

#2138 fix: correct usage of user id & session id
  python/instrumentation/openinference-instrumentation-agno/pyproject.toml
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
  python/scripts/select_tox_environments.py
Labels: size:M, lgtm

#2137 docs: converge spec to Python OpenAI practice
  spec/README.md
  spec/configuration.md
  spec/embedding_spans.md
  spec/llm_spans.md
  spec/multimodal_attributes.md
  spec/semantic_conventions.md
  spec/tool_calling.md
Labels: size:L, lgtm

#2151 feat(openlit): openlit span processor
  python/instrumentation/openinference-instrumentation-openlit/src/openinference/instrumentation/openlit/_span_processor.py
Labels: size:XS

#2148 fix(beeaI): dedupe traces/spans
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/base.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/tool.py
Labels: size:M, lgtm
