Repository Arize-ai/openinference, pull requests merged in 2025-06, with the labels that each got.

#1742 fix: Added exception to span when invoke_agent throws an exception
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_wrappers.py
Labels: size:XS

#1730 feat: Add model name and provider fields to DSPy for better model tracking/instrumentation #1730
  python/instrumentation/openinference-instrumentation-dspy/.gitignore
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/conftest.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_real_lm_classes.py
Labels: size:L

#1744 fix(smolagents): instrument both __call__ and generate methods for complete model tracing
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:M

#1759 feat: add instrumentation for google-adk
  README.md
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-google-adk/LICENSE
  python/instrumentation/openinference-instrumentation-google-adk/README.md
  python/instrumentation/openinference-instrumentation-google-adk/examples/multi_tool_agent/__init__.py
  python/instrumentation/openinference-instrumentation-google-adk/examples/multi_tool_agent/agent.py
  python/instrumentation/openinference-instrumentation-google-adk/examples/storyflow_agent.py
  python/instrumentation/openinference-instrumentation-google-adk/examples/tools.py
  python/instrumentation/openinference-instrumentation-google-adk/pyproject.toml
  python/instrumentation/openinference-instrumentation-google-adk/src/openinference/instrumentation/google_adk/__init__.py
  python/instrumentation/openinference-instrumentation-google-adk/src/openinference/instrumentation/google_adk/_wrappers.py
  python/instrumentation/openinference-instrumentation-google-adk/src/openinference/instrumentation/google_adk/py.typed
  python/instrumentation/openinference-instrumentation-google-adk/src/openinference/instrumentation/google_adk/version.py
  python/instrumentation/openinference-instrumentation-google-adk/test-requirements.txt
  python/instrumentation/openinference-instrumentation-google-adk/tests/cassettes/test_google_adk_instrumentor.yaml
  python/instrumentation/openinference-instrumentation-google-adk/tests/conftest.py
  python/instrumentation/openinference-instrumentation-google-adk/tests/test_entrypoint.py
  python/instrumentation/openinference-instrumentation-google-adk/tests/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-google-adk/tests/test_uninstrument.py
  python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
  python/tox.ini
  release-please-config.json
Labels: size:XXL

#1765 chore: ignore .gitignore for release please
  release-please-config.json
Labels: size:XS

#1774 feat(semcov): Update input and output cost
  js/.changeset/brave-regions-peel.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_attributes.py
  spec/semantic_conventions.md
Labels: size:L

#1782 fix: Enable sampling when using OpenInference tracer
  python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py
  python/openinference-instrumentation/tests/test_manual_instrumentation.py
Labels: size:L

#1760 fix(bedrock): fixing invoke model api calls
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_invoke_model_messages_api.py
  python/instrumentation/openinference-instrumentation-bedrock/examples/tool_call.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/_extract_invoke_model_attributes.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/_attributes.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/TestClaudeInvokeModelMessageApi.test_invoke_model.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/TestClaudeInvokeModelMessageApi.test_invoke_model_with_image.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/test_invoke_model_claude_message_api.py
Labels: size:XXL

#1797 feat(openai-js): Support OpenAI SDK 5.x
  js/.changeset/shy-sides-shake.md
  js/packages/openinference-instrumentation-openai/package.json
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/src/responsesAttributes.ts
  js/packages/openinference-instrumentation-openai/test/openai.responses.test.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/pnpm-lock.yaml
Labels: size:L

#1801 feat(openai): Add support for chat.parse and responses.parse
  js/.changeset/stale-gifts-teach.md
  js/packages/openinference-instrumentation-openai/README.md
  js/packages/openinference-instrumentation-openai/examples/responses.ts
  js/packages/openinference-instrumentation-openai/package.json
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.responses.test.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
  js/pnpm-lock.yaml
Labels: size:L

#1809 feat: Prioritize subclasses method wrapping to prevent multiple spans
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/__init__.py
Labels: size:S

#1814 feat(semconv): add semconv providers for xai and deepseek
  js/.changeset/thirty-pots-help.md
  js/packages/openinference-instrumentation-openai/README.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
Labels: lgtm
