Repository Arize-ai/openinference, pull requests merged in 2025-01, with the labels that each got.

#1183 fix(llama-index): coerce token counts to be integers
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:M

#1184 feat: working instrumentation with smolagents
  python/instrumentation/openinference-instrumentation-smolagents/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-smolagents/LICENSE
  python/instrumentation/openinference-instrumentation-smolagents/README.md
  python/instrumentation/openinference-instrumentation-smolagents/examples/e2b_example.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/managed_agent.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/openai_model.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/openai_model_tool_call.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/rag.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-smolagents/examples/text2sql.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/tool_calling_agent.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/tool_invocation.py
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/py.typed
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/version.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_openai_server_model_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_openai_server_model_with_tool_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
  python/tox.ini
Labels: size:XXL

#1194 ci: set up release please for smolagents
  release-please-config.json
Labels: size:XS

#1188 fix: Add support for output messages for sync/async
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
  python/tox.ini
Labels: size:M

#1205 fix(haystack): ensure compatibility with haystack 2.9
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/cassettes/test_instrumentor/test_openai_document_embedder_embedding_span_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
  python/tox.ini
Labels: size:S, size:M

#1211 feat: basic instrumentation for autogen (ag2)
  python/instrumentation/openinference-instrumentation-autogen/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-autogen/LICENSE
  python/instrumentation/openinference-instrumentation-autogen/README.md
  python/instrumentation/openinference-instrumentation-autogen/examples/ex.py
  python/instrumentation/openinference-instrumentation-autogen/pyproject.toml
  python/instrumentation/openinference-instrumentation-autogen/src/openinference/instrumentation/autogen/__init__.py
  python/instrumentation/openinference-instrumentation-autogen/src/openinference/instrumentation/autogen/version.py
  python/tox.ini
  release-please-config.json
Labels: size:L

#1213 fix: remove token on crewai kickoff chain span
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
  python/tox.ini
Labels: size:M

#1216 feat(autogen2): basic tool calling
  python/instrumentation/openinference-instrumentation-autogen/examples/ex.py
  python/instrumentation/openinference-instrumentation-autogen/src/openinference/instrumentation/autogen/__init__.py
Labels: size:M

#1218 fix(autogen2): tool calling fix
  python/instrumentation/openinference-instrumentation-autogen/src/openinference/instrumentation/autogen/__init__.py
Labels: size:XS

#1222 fix: fix broken tests when using latest crewai
  python/tox.ini
Labels: size:XS

#1221 fix(AG2): CI fix
  python/instrumentation/openinference-instrumentation-autogen/examples/ex.py
  python/instrumentation/openinference-instrumentation-autogen/src/openinference/instrumentation/autogen/__init__.py
  python/instrumentation/openinference-instrumentation-autogen/tests/test_instrumentor.py
Labels: size:L

#1147 feat: openinference tracer
  python/openinference-instrumentation/examples/requirements.txt
  python/openinference-instrumentation/examples/tracer.ipynb
  python/openinference-instrumentation/pyproject.toml
  python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/src/openinference/instrumentation/context_attributes.py
  python/openinference-instrumentation/src/openinference/instrumentation/logging.py
  python/openinference-instrumentation/tests/conftest.py
  python/openinference-instrumentation/tests/test_config.py
  python/openinference-instrumentation/tests/test_manual_instrumentation.py
Labels: size:XXL

#1229 fix(smolagents): update internal smolagents import for compatibility with versions post 1.5.0
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Labels: size:S

#1234 fix: Fix missing token counts when using VertexAI with Langchain Instrumentor
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_gemini_token_counts.yaml
  python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_gemini_token_counts_streaming.yaml
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:L

#1239 fix(smolagents): remove redundant smolagents llm output.value causing warning
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Labels: size:XS

#1240 feat: support bedrock anthropic messages via invoke_model_with_stream_response
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/scripts/codegen/anthropic/anthropic_schema.json
  python/instrumentation/openinference-instrumentation-bedrock/scripts/codegen/anthropic/json_schema.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__generated__/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__generated__/anthropic/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__generated__/anthropic/_types.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_proxy.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_wrappers.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/_messages.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/cassettes/TestInvokeModelWithStreamResponse.test_invoke.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/conftest.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_invoke_model_with_stream_response.py
  python/tox.ini
Labels: size:XXL

#1236 fix(smolagents): use correct smolagents tool schema extraction function
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:M

#1243 fix(smolagents): ensure tool attributes are captured successfully on new versions of smolagents
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
Labels: size:XS

#1245 ci: fix cassettes for bedrock unit tests
  python/instrumentation/openinference-instrumentation-bedrock/tests/cassettes/TestInvokeModelWithStreamResponse.test_invoke.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_invoke_model_with_stream_response.py
Labels: size:L

#1244 feat: Add prompt-related semantic conventions
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_attributes.py
Labels: size:M
