Repository Arize-ai/openinference, pull requests merged in 2025-03, with the labels that each got.

#1320 fix: image source types for anthropic 0.49
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/_messages.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_invoke_model_with_stream_response.py
Labels: size:S

#1324 chore(js): add lock file for nextjs example
  js/examples/nextjs-openai-simple/README.md
  js/examples/nextjs-openai-simple/next.config.js
  js/examples/nextjs-openai-simple/package-lock.json
  js/examples/nextjs-openai-simple/package.json
Labels: size:S

#1325 chore(js): update changesets
  js/package.json
  js/pnpm-lock.yaml
Labels: size:XS

#1326 fix(dspy): fix dependancies
  python/examples/dspy-rag-fastapi/backend/pyproject.toml
  python/examples/dspy-rag-fastapi/frontend/Dockerfile
  python/examples/dspy-rag-fastapi/frontend/poetry.lock
  python/examples/dspy-rag-fastapi/frontend/pyproject.toml
Labels: size:S

#1328 fix(langchainjs): deprecate v0.1 support for security reasons
  js/.changeset/cute-clouds-tell.md
  js/packages/openinference-instrumentation-langchain/README.md
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/instrumentation.ts
  js/packages/openinference-instrumentation-langchain/src/instrumentationUtils.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV1.test.ts
  js/pnpm-lock.yaml
Labels: size:XL

#1337 fix: message content when it's list of strings
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:M

#1339 docs(langchain.js): fix formatting
  js/packages/openinference-instrumentation-langchain/examples/README.md
Labels: size:XS

#1340 fix: handle missing attribute if .instrument() has not been called and tracer has not been initialized
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/__init__.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:S

#1349 ci: Update cla.yaml to add dependabot
  .github/workflows/cla.yaml
Labels: size:XS

#1353 docs: fix license to be openinference
  python/instrumentation/openinference-instrumentation-anthropic/LICENSE
  python/instrumentation/openinference-instrumentation-autogen/LICENSE
  python/instrumentation/openinference-instrumentation-bedrock/LICENSE
  python/instrumentation/openinference-instrumentation-crewai/LICENSE
  python/instrumentation/openinference-instrumentation-dspy/LICENSE
  python/instrumentation/openinference-instrumentation-groq/LICENSE
  python/instrumentation/openinference-instrumentation-guardrails/LICENSE
  python/instrumentation/openinference-instrumentation-haystack/LICENSE
  python/instrumentation/openinference-instrumentation-instructor/LICENSE
  python/instrumentation/openinference-instrumentation-langchain/LICENSE
  python/instrumentation/openinference-instrumentation-litellm/LICENSE
  python/instrumentation/openinference-instrumentation-llama-index/LICENSE
  python/instrumentation/openinference-instrumentation-mistralai/LICENSE
  python/instrumentation/openinference-instrumentation-openai/LICENSE
  python/instrumentation/openinference-instrumentation-smolagents/LICENSE
  python/instrumentation/openinference-instrumentation-vertexai/LICENSE
  python/openinference-instrumentation/LICENSE
  python/openinference-semantic-conventions/LICENSE
Labels: size:XS

#1359 fix: Security Issues in Llama Index Example
  python/examples/llama-index/backend/poetry.lock
  python/examples/llama-index/backend/pyproject.toml
  python/examples/llama-index/frontend/package-lock.json
Labels: size:XS, dependencies

#1350 feat: openai-agents instrumentation
  python/instrumentation/openinference-instrumentation-openai-agents/LICENSE
  python/instrumentation/openinference-instrumentation-openai-agents/README.md
  python/instrumentation/openinference-instrumentation-openai-agents/examples/handoffs/message_filter.py
  python/instrumentation/openinference-instrumentation-openai-agents/examples/handoffs/message_filter_streaming.py
  python/instrumentation/openinference-instrumentation-openai-agents/examples/hello_world.py
  python/instrumentation/openinference-instrumentation-openai-agents/examples/tutor.py
  python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/__init__.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/package.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/py.typed
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/version.py
  python/instrumentation/openinference-instrumentation-openai-agents/test-requirements.txt
  python/instrumentation/openinference-instrumentation-openai-agents/tests/__init__.py
  python/instrumentation/openinference-instrumentation-openai-agents/tests/conftest.py
  python/instrumentation/openinference-instrumentation-openai-agents/tests/test_instrumentor.py
  python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
  python/tox.ini
Labels: size:XXL

#1360 ci: add openai-agents to release please configuration
  release-please-config.json
Labels: size:XS

#1309 feat(beeai): add beeai js instrumentation package
  .github/workflows/typescript-CI.yaml
  .github/workflows/typescript-publish.yaml
  README.md
  js/.changeset/salty-memes-sit.md
  js/examples/langchain-express/frontend/app/globals.css
  js/examples/llama-index-express/frontend/app/globals.css
  js/examples/next-openai-telemetry-app/app/globals.css
  js/examples/openai/frontend/app/globals.css
  js/packages/openinference-instrumentation-beeai/LICENSE
  js/packages/openinference-instrumentation-beeai/README.md
  js/packages/openinference-instrumentation-beeai/examples/README.md
  js/packages/openinference-instrumentation-beeai/examples/bee.ts
  js/packages/openinference-instrumentation-beeai/examples/instrumentation.ts
  js/packages/openinference-instrumentation-beeai/jest.config.ts
  js/packages/openinference-instrumentation-beeai/package-lock.json
  js/packages/openinference-instrumentation-beeai/package.json
  js/packages/openinference-instrumentation-beeai/src/config.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/buildTraceTree.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/create-span.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/getErrorSafe.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/idNameManager.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/traceSerializer.ts
  js/packages/openinference-instrumentation-beeai/src/index.ts
  js/packages/openinference-instrumentation-beeai/src/instrumentation.ts
  js/packages/openinference-instrumentation-beeai/src/middleware.ts
  js/packages/openinference-instrumentation-beeai/src/types.ts
  js/packages/openinference-instrumentation-beeai/test/idNameManager.test.ts
  js/packages/openinference-instrumentation-beeai/test/traceSerializer.test.ts
  js/packages/openinference-instrumentation-beeai/tsconfig.esm.json
  js/packages/openinference-instrumentation-beeai/tsconfig.esnext.json
  js/packages/openinference-instrumentation-beeai/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XXL

#1361 ci: fix langchain test
  js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts
Labels: size:XS

#1358 fix: Security Issues in DSPy RAG FastAPI Backend
  .gitignore
  python/examples/dspy-rag-fastapi/backend/Dockerfile
  python/examples/dspy-rag-fastapi/backend/poetry.lock
  python/examples/dspy-rag-fastapi/backend/pyproject.toml
Labels: size:XS, dependencies

#1307 fix(liteLLM): support sync stream
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
Labels: size:L

#1366 fix: fix js openai image attribute path
  js/.changeset/rude-turkeys-search.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
Labels: size:XS

#1368 docs: openai agents
  README.md
Labels: size:M

#1373 fix: attach span to context
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Labels: size:XS

#1374 fix: reclassify handoff span as tool span
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Labels: size:XS

#1385 fix: replace logger.exception() with repr()
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
Labels: size:XS

#1308 fix: Add support for litellm Message type
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
Labels: size:M

#1394 feat(beeai): add support for llm and tool modules
  README.md
  js/.changeset/three-tables-occur.md
  js/packages/openinference-instrumentation-beeai/examples/README.md
  js/packages/openinference-instrumentation-beeai/examples/run-agent.ts
  js/packages/openinference-instrumentation-beeai/examples/run-llm.ts
  js/packages/openinference-instrumentation-beeai/examples/run-tool.ts
  js/packages/openinference-instrumentation-beeai/package.json
  js/packages/openinference-instrumentation-beeai/src/config.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/buildTraceTree.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts
  js/packages/openinference-instrumentation-beeai/src/instrumentation.ts
  js/packages/openinference-instrumentation-beeai/src/middleware.ts
  js/pnpm-lock.yaml
Labels: size:L

#1403 fix: only import exported smolagents models
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
Labels: size:S

#1406 fix(beeai): remove deprecated instrumentation logger
  js/.changeset/plain-poems-lick.md
  js/packages/openinference-instrumentation-beeai/package.json
  js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts
  js/pnpm-lock.yaml
Labels: size:S

#1408 fix: add span attributes for FunctionSpanData
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Labels: size:S

#1411 test: openinference tracer respects otel disabled flag
  python/openinference-instrumentation/tests/conftest.py
  python/openinference-instrumentation/tests/test_manual_instrumentation.py
Labels: size:S

#1417 feat(beeai): update examples docs
  js/packages/openinference-instrumentation-beeai/examples/README.md
Labels: size:S

#1419 fix: openai agent with int tool return
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Labels: size:XS

#1413 refactor: move tracer-related code into sub-modules
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/_attributes.py
  python/openinference-instrumentation/src/openinference/instrumentation/_spans.py
  python/openinference-instrumentation/src/openinference/instrumentation/_tracer_providers.py
  python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py
  python/openinference-instrumentation/src/openinference/instrumentation/_types.py
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/test_config.py
  python/openinference-instrumentation/tests/test_manual_instrumentation.py
Labels: size:XXL

#1415 fix: add type stubs for openinference span
  python/openinference-instrumentation/src/openinference/instrumentation/_spans.pyi
  python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py
  python/openinference-instrumentation/tests/test_config.py
Labels: size:M

#1426 fix: get attributes from GenerationSpanData (i.e. chat completions api)
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Labels: size:L

#1425 fix(beeai): empty data serialization
  js/.changeset/bumpy-breads-look.md
  js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts
  js/packages/openinference-instrumentation-beeai/src/middleware.ts
Labels: size:XL

#1429 fix: include cache tokens in prompt tokens for anthropic
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/__init__.py
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/test-requirements.txt
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/anthropic/_messages.py
Labels: size:M

#1393 feat(semcov): token counts for cached prompts and reasoning steps in the completion
  js/.changeset/silent-pots-begin.md
  js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_attributes.py
  spec/semantic_conventions.md
Labels: size:L

#1434 feat(beeai): add support for toolcalling agent
  README.md
  js/.changeset/four-wings-tell.md
  js/packages/openinference-instrumentation-beeai/examples/README.md
  js/packages/openinference-instrumentation-beeai/examples/run-react-agent.ts
  js/packages/openinference-instrumentation-beeai/examples/run-toolcalling-agent.ts
  js/packages/openinference-instrumentation-beeai/src/helpers/getSerializedObjectSafe.ts
  js/packages/openinference-instrumentation-beeai/src/middleware.ts
Labels: size:M

#1439 ci: ensure ci runs for all instrumentors when changes are made to base dependencies
  .github/workflows/python-CI.yaml
  python/scripts/select_tox_environments.py
  python/tox.ini
Labels: size:L

#1440 ci: fix failing tests py39-ci-openai_agents-latest and py39-ci-dspy-latest
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
  python/instrumentation/openinference-instrumentation-openai-agents/test-requirements.txt
Labels: size:XS

#1441 fix: ensure `OpenInferenceSpan` is an instance of `opentelemetry.trace.Span` for type checks
  python/openinference-instrumentation/src/openinference/instrumentation/_spans.pyi
  python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py
  python/openinference-instrumentation/tests/test_config.py
  python/scripts/select_tox_environments.py
  python/tox.ini
Labels: size:S

#1446 feat!: support chat message content blocks for llama-index >= 0.12.3
  python/instrumentation/openinference-instrumentation-llama-index/README.md
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_message_content_blocks.py
  python/tox.ini
Labels: size:L

#1450 fix(openai): Rewrite namespace import to default import
  js/.changeset/large-pants-switch.md
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
Labels: size:XS
