Repository Arize-ai/openinference, pull requests merged in 2025-04, with the labels that each got.

#1458 feat: capture result from MCPListToolsSpanData
  python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/package.py
  python/instrumentation/openinference-instrumentation-openai-agents/test-requirements.txt
  python/instrumentation/openinference-instrumentation-openai-agents/tests/test_span_attribute_helpers.py
Labels: size:XXL

#1447 refactor: (crewAI) Support handle response attribute properly
  python/instrumentation/openinference-instrumentation-crewai/README.md
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session_context_attributes.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/test_instrumentor.py
Labels: size:XXL, lgtm

#1461 feat: cached and reasoning tokens from response api
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
  python/instrumentation/openinference-instrumentation-openai-agents/tests/test_span_attribute_helpers.py
Labels: size:M

#1465 feat: instrumentation-anthropic cache token counts
  python/instrumentation/openinference-instrumentation-anthropic/src/openinference/instrumentation/anthropic/_wrappers.py
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/cassettes/test_instrumentor/test_anthropic_instrumentation_messages_token_counts.yaml
  python/instrumentation/openinference-instrumentation-anthropic/tests/openinference/anthropic/test_instrumentor.py
Labels: size:L

#1471 feat(langchainjs): capture reasoning, cache, and audio tokens
  js/packages/openinference-instrumentation-langchain/examples/reasoning.ts
  js/packages/openinference-instrumentation-langchain/package.json
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts
  js/packages/openinference-instrumentation-openai/examples/embed.ts
  js/pnpm-lock.yaml
Labels: size:M

#1469 feat(openai-node-sdk): prompt and completion cache / reasoning / audio tokens
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/test/openai.test.ts
Labels: size:M

#1472 chore: add js changeset
  js/.changeset/few-rings-search.md
Labels: size:XS

#1486 fix: Tracing Issues in DSPy RAG FastAPI Example
  python/examples/dspy-rag-fastapi/backend/app/utils/rag_functions.py
  python/examples/dspy-rag-fastapi/backend/instrument.py
  python/examples/dspy-rag-fastapi/backend/poetry.lock
  python/examples/dspy-rag-fastapi/backend/pyproject.toml
  python/examples/dspy-rag-fastapi/frontend/pages/1_zero_shot_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/2_compiled_query.py
  python/examples/dspy-rag-fastapi/frontend/pages/3_optimize_pipeline.py
Labels: examples, size:M, dependencies

#1485 feat: add cached read semantic conventions to openai sdk
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/cassettes/test_cached_tokens.yaml
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_tool_calls.py
Labels: size:L, lgtm

#1480 feat(langchainpy): capture reasoning, cache, and audio tokens
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_token_counts.yaml
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:L

#1488 fix: tuple message type
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:XS

#1416 fix: allow prerelease versions of smolagents
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
Labels: size:XS

#1497 fix: merge metadata
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-langchain/tests/test_merged_metadata.py
Labels: size:M

#1502 fix: ensure io attributes output by manual instrumentation helpers are always strings
  python/openinference-instrumentation/src/openinference/instrumentation/_attributes.py
Labels: size:S

#1489 feat(llama-index py): capture reasoning, cache, and audio tokens
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_callback.py
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestTokenCounts.test_anthropic.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestTokenCounts.test_groq.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/TestTokenCounts.test_openai.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/cassettes/test_groq_astream_chat_token_count.yaml
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_token_counts.py
Labels: size:XL

#1507 fix: increased minimum supported version of openinference-instrumentation to 0.1.27
  python/instrumentation/openinference-instrumentation-anthropic/pyproject.toml
  python/instrumentation/openinference-instrumentation-autogen/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-groq/pyproject.toml
  python/instrumentation/openinference-instrumentation-guardrails/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-instructor/pyproject.toml
  python/instrumentation/openinference-instrumentation-langchain/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-mistralai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai-agents/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-vertexai/pyproject.toml
Labels: size:M

#1509 fix: capture tools from chat kwargs
  python/dev-requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/pyproject.toml
  python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py
  python/instrumentation/openinference-instrumentation-llama-index/test-requirements.txt
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/conftest.py
  python/instrumentation/openinference-instrumentation-llama-index/tests/openinference/instrumentation/llama_index/test_chat_with_tools.py
  python/tox.ini
Labels: size:L

#1495 feat: portkey chat completions
  python/instrumentation/openinference-instrumentation-portkey/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-portkey/README.md
  python/instrumentation/openinference-instrumentation-portkey/pyproject.toml
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/__init__.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_utils.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_with_span.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_wrappers.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/version.py
  python/instrumentation/openinference-instrumentation-portkey/test-requirements.txt
  python/instrumentation/openinference-instrumentation-portkey/tests/cassettes/test_chat_completion.yaml
  python/instrumentation/openinference-instrumentation-portkey/tests/conftest.py
  python/instrumentation/openinference-instrumentation-portkey/tests/test_instrumentor.py
  python/tox.ini
Labels: size:XL, lgtm

#1512 ci: portkey release please
  release-please-config.json
Labels: size:XS, lgtm

#1510 feat(langchain-js): Instrument langchain tool messages
  js/.changeset/some-dots-greet.md
  js/packages/openinference-instrumentation-langchain/src/utils.ts
Labels: size:XS

#1517 fix: record exceptions for on spans
  js/.changeset/many-olives-cross.md
  js/packages/openinference-instrumentation-langchain/src/tracer.ts
Labels: size:XS

#1496 feat: beeai python package
  README.md
  python/instrumentation/openinference-instrumentation-beeai/README.md
  python/instrumentation/openinference-instrumentation-beeai/examples/llm_basic.py
  python/instrumentation/openinference-instrumentation-beeai/examples/openinference_setup.py
  python/instrumentation/openinference-instrumentation-beeai/examples/react_agent_basic.py
  python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-beeai/examples/tool_basic.py
  python/instrumentation/openinference-instrumentation-beeai/examples/toolcalling_agent_basic.py
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/middleware.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/utils/build_trace_tree.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/utils/create_span.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/utils/get_serialized_object_safe.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/utils/id_name_manager.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/version.py
  python/instrumentation/openinference-instrumentation-beeai/tests/test_create_span.py
  python/instrumentation/openinference-instrumentation-beeai/tests/test_id_name_manager.py
  python/instrumentation/openinference-instrumentation-beeai/uv.lock
  python/tox.ini
  release-please-config.json
Labels: size:XXL

#1516 feat: reasoning, cache, audio token counts litellm
  python/instrumentation/openinference-instrumentation-litellm/pyproject.toml
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/cassettes/TestTokenCounts.test_anthropic.yaml
  python/instrumentation/openinference-instrumentation-litellm/tests/cassettes/TestTokenCounts.test_openai.yaml
  python/instrumentation/openinference-instrumentation-litellm/tests/conftest.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_token_counts.py
Labels: size:L, lgtm

#1522 fix: beeai python package
  python/instrumentation/openinference-instrumentation-beeai/README.md
  python/instrumentation/openinference-instrumentation-beeai/examples/react_agent_basic.py
  python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-beeai/examples/toolcalling_agent_basic.py
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/uv.lock
Labels: size:M

#1521 feat: instrument OpenAI responses API
  python/instrumentation/openinference-instrumentation-openai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-openai/examples/responses.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_multimodal.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_multimodal_with_config.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_stream.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_with_async.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_with_async_stream.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_with_file_search_tool.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_with_function_calling.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_with_structured_outputs.py
  python/instrumentation/openinference-instrumentation-openai/examples/responses_with_websearch_tool.py
  python/instrumentation/openinference-instrumentation-openai/pyproject.toml
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_attributes/__init__.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_attributes/_responses_api.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/package.py
  python/instrumentation/openinference-instrumentation-openai/test-requirements.txt
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_create_param_base.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_function_tool_call.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_input_param.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_output_message.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_output_refusal.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_output_refusal_param.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_output_text.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_output_text_param.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_reasoning_item.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_reasoning_item_param.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_usage.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
  python/tox.ini
Labels: size:XXL

#1526 feat(beeai): fix latest js framework version
  js/.changeset/plenty-humans-kneel.md
  js/packages/openinference-instrumentation-beeai/examples/instrumentation.ts
  js/packages/openinference-instrumentation-beeai/package.json
  js/packages/openinference-instrumentation-beeai/src/instrumentation.ts
  js/pnpm-lock.yaml
Labels: size:M

#1515 chore: manual llm spans notebook
  python/openinference-instrumentation/examples/manual_llm_spans.ipynb
  python/openinference-instrumentation/examples/tracer.ipynb
Labels: size:XL

#1524 feat(mcp): mcp python context propagation
  .release-please-manifest.json
  python/instrumentation/openinference-instrumentation-mcp/LICENSE
  python/instrumentation/openinference-instrumentation-mcp/README.md
  python/instrumentation/openinference-instrumentation-mcp/pyproject.toml
  python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/__init__.py
  python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/package.py
  python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/version.py
  python/instrumentation/openinference-instrumentation-mcp/test-requirements.txt
  python/instrumentation/openinference-instrumentation-mcp/tests/collector.py
  python/instrumentation/openinference-instrumentation-mcp/tests/conftest.py
  python/instrumentation/openinference-instrumentation-mcp/tests/mcpserver.py
  python/instrumentation/openinference-instrumentation-mcp/tests/test_instrumenter.py
  python/tox.ini
  release-please-config.json
Labels: size:L

#1525 feat: update beeai framework package
  python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/uv.lock
Labels: size:XS

#1363 feat: Add bedrock-agent instrumentation
  python/instrumentation/openinference-instrumentation-bedrock/DEVELOPER.md
  python/instrumentation/openinference-instrumentation-bedrock/README.md
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_agent.py
  python/instrumentation/openinference-instrumentation-bedrock/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_wrappers.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/TestInvokeModelWithStreamResponse.test_invoke.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_agent_call_without_traces.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_knowledge_base_results.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_post_processing_trace.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_preprocessing_trace.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_tool_calls_with_input_params.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_tool_calls_without_input_params.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/test_invoke_agent_instrumentor.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/test_invoke_model_with_stream_response.py
Labels: size:XXL

#1536 feat: mcp js context propagation
  js/.changeset/pink-pillows-carry.md
  js/packages/openinference-instrumentation-mcp/README.md
  js/packages/openinference-instrumentation-mcp/jest.config.js
  js/packages/openinference-instrumentation-mcp/package.json
  js/packages/openinference-instrumentation-mcp/src/index.ts
  js/packages/openinference-instrumentation-mcp/src/mcp.ts
  js/packages/openinference-instrumentation-mcp/test/collector.ts
  js/packages/openinference-instrumentation-mcp/test/mcp.test.ts
  js/packages/openinference-instrumentation-mcp/test/mcpserver.ts
  js/packages/openinference-instrumentation-mcp/tsconfig.esm.json
  js/packages/openinference-instrumentation-mcp/tsconfig.esnext.json
  js/packages/openinference-instrumentation-mcp/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XL

#1540 docs: add portkey, mcp to top level readme
  README.md
Labels: size:S

#1533 feat(openai-js): Instrument openai responses api
  js/.changeset/slimy-pumas-rescue.md
  js/packages/openinference-instrumentation-openai/README.md
  js/packages/openinference-instrumentation-openai/examples/manual-instrumentation.ts
  js/packages/openinference-instrumentation-openai/examples/responses.ts
  js/packages/openinference-instrumentation-openai/package.json
  js/packages/openinference-instrumentation-openai/src/instrumentation.ts
  js/packages/openinference-instrumentation-openai/src/responsesAttributes.ts
  js/packages/openinference-instrumentation-openai/test/openai.responses.test.ts
  js/pnpm-lock.yaml
Labels: size:XXL

#1547 feat: Openai audio + reasoning token counts
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/cassettes/TestTokenCounts.test_openai.yaml
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_token_counts.py
Labels: size:L, lgtm

#1553 fix(deps): bump next.js minor version to address Dependabot alerts
  js/examples/nextjs-openai-simple/package-lock.json
  js/examples/nextjs-openai-simple/package.json
  python/examples/llama-index/frontend/package-lock.json
  python/examples/llama-index/frontend/package.json
Labels: size:XS

#1549 fix: instructor output bug fix
  python/instrumentation/openinference-instrumentation-instructor/src/openinference/instrumentation/instructor/_wrappers.py
  python/tox.ini
Labels: size:M

#1555 feat(mcp-js): move instrumentation to transport layer
  js/packages/openinference-instrumentation-mcp/README.md
  js/packages/openinference-instrumentation-mcp/package.json
  js/packages/openinference-instrumentation-mcp/src/mcp.ts
  js/packages/openinference-instrumentation-mcp/test/mcp.test.ts
  js/packages/openinference-instrumentation-mcp/test/mcpserver.ts
  js/pnpm-lock.yaml
Labels: size:XL

#1556 fix(openai_agents): Set status `on_span_end`.
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/_processor.py
Labels: size:S

#1557 chore: add mcp release changeset
  js/.changeset/few-waves-know.md
Labels: size:XS

#1560 fix: removes spurious print(2) from python beeai and converts rest to loggers
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/middleware.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/utils/get_serialized_object_safe.py
Labels: size:S

#1562 fix: Start span before API call
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
Labels: size:M

#1571 fix(litellm): remove sensitive info from invocation params
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/cassettes/TestTokenCounts.test_openai.yaml
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_token_counts.py
Labels: size:L

#1575 chore(langchain): add examples as to how to delete messages
  python/instrumentation/openinference-instrumentation-langchain/examples/message_deletion.py
  python/instrumentation/openinference-instrumentation-langchain/examples/requirements.txt
Labels: size:L
