Repository Arize-ai/openinference, pull requests merged in 2025-05, with the labels that each got.

#1576 feat(beeai): updates so we can run 0.1.19
  python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/uv.lock
Labels: size:XS

#1587 fix: support function call parts when streaming
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_accumulator.py
  python/instrumentation/openinference-instrumentation-vertexai/src/openinference/instrumentation/vertexai/_wrapper.py
  python/instrumentation/openinference-instrumentation-vertexai/tests/test_gapic_client.py
Labels: size:L

#1500 feat: add Google GenAI instrumentation
  README.md
  python/instrumentation/openinference-instrumentation-google-genai/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-google-genai/LICENSE
  python/instrumentation/openinference-instrumentation-google-genai/README.md
  python/instrumentation/openinference-instrumentation-google-genai/examples/generate_content.py
  python/instrumentation/openinference-instrumentation-google-genai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-google-genai/examples/send_message_multi_turn.py
  python/instrumentation/openinference-instrumentation-google-genai/pyproject.toml
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/__init__.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_stream.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_utils.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_with_span.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_wrappers.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/package.py
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/version.py
  python/instrumentation/openinference-instrumentation-google-genai/test-requirements.txt
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_async_generate_content.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_async_streaming_text_content.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_generate_content.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_multi_turn_conversation.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_streaming_text_content.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_sync_generate_content.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/test_instrumentation.py
  python/tox.ini
  release-please-config.json
Labels: size:XXL

#1579 chore(js): Publish experimental js packages on pull requests
  .github/workflows/typescript-packages-publish-experimental.yml
Labels: size:M

#1605 docs: fix google genai import in README
  python/instrumentation/openinference-instrumentation-google-genai/README.md
Labels: size:XS

#1597 feat(dspy): Add initial support for async tracing
  python/instrumentation/openinference-instrumentation-dspy/examples/async.py
  python/instrumentation/openinference-instrumentation-dspy/examples/async_custom.py
  python/instrumentation/openinference-instrumentation-dspy/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-dspy/pyproject.toml
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_rag_module[False].yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_rag_module[True].yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XL

#1603 feat: Agno instrumentor
  .release-please-manifest.json
  README.md
  python/instrumentation/openinference-instrumentation-agno/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-agno/LICENSE
  python/instrumentation/openinference-instrumentation-agno/README.md
  python/instrumentation/openinference-instrumentation-agno/examples/basic_agent_with_tools.py
  python/instrumentation/openinference-instrumentation-agno/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-agno/pyproject.toml
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/__init__.py
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/py.typed
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/version.py
  python/instrumentation/openinference-instrumentation-agno/tests/__init__.py
  python/instrumentation/openinference-instrumentation-agno/tests/openinference/instrumentation/agno/fixtures/agent_run.yaml
  python/instrumentation/openinference-instrumentation-agno/tests/test_instrumentor.py
  python/openinference-instrumentation/examples/manual_llm_spans.ipynb
  python/openinference-instrumentation/examples/tracer.ipynb
  python/tox.ini
  release-please-config.json
Labels: size:XXL

#1614 fix: Agno duplicate model invoke
  python/instrumentation/openinference-instrumentation-agno/examples/basic_agent_with_tools.py
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/__init__.py
  python/instrumentation/openinference-instrumentation-agno/tests/test_instrumentor.py
Labels: size:S

#1617 feat(dspy): Instrument DSPy.Tool
  python/instrumentation/openinference-instrumentation-dspy/examples/tools.py
  python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_react[False].yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/cassettes/test_instrumentor/test_react[True].yaml
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:XL

#1618 refactor: Add better LLM instrumentation for Agno Instrumentor
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
Labels: size:M

#1624 fix: Cleanup openinference-vercel readme, pinned versions, old typescript types
  js/.changeset/many-needles-create.md
  js/packages/openinference-vercel/README.md
  js/packages/openinference-vercel/package.json
  js/packages/openinference-vercel/src/OpenInferenceSpanProcessor.ts
  js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
  js/pnpm-lock.yaml
Labels: size:M

#1623 fix(haystack): fixing ci issues for haystack-ai
  python/instrumentation/openinference-instrumentation-haystack/pyproject.toml
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/__init__.py
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:M

#1627 ci: pin changesets
  .github/workflows/typescript-publish.yaml
Labels: size:XS

#1586 feat(openai-agents): add support for exclusive processor configuration
  python/instrumentation/openinference-instrumentation-openai-agents/src/openinference/instrumentation/openai_agents/__init__.py
Labels: size:S

#1634 fix(mcp): support mcp>=1.8.0 with new SessionMessage structure
  python/instrumentation/openinference-instrumentation-mcp/pyproject.toml
  python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/__init__.py
  python/instrumentation/openinference-instrumentation-mcp/test-requirements.txt
Labels: size:S

#1629 docs: update readmes for development setup and fixes
  CONTRIBUTING
  python/DEVELOPMENT.md
  python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
Labels: size:S

#1625 chore: Bump CI node versions
  .github/workflows/typescript-CI.yaml
  .github/workflows/typescript-packages-publish-experimental.yml
  js/.nvmrc
  js/DEVELOPMENT.md
Labels: size:S

#1640 feat(mcp): add instrumentation support for Streamable-HTTP transport and bump mcp dependency to ≥1.8.1
  python/instrumentation/openinference-instrumentation-mcp/pyproject.toml
  python/instrumentation/openinference-instrumentation-mcp/src/openinference/instrumentation/mcp/__init__.py
  python/instrumentation/openinference-instrumentation-mcp/test-requirements.txt
  python/instrumentation/openinference-instrumentation-mcp/tests/mcpserver.py
  python/instrumentation/openinference-instrumentation-mcp/tests/test_instrumenter.py
Labels: size:M

#1643 feat(langchain): track tool schemas from LLM invocation parameters
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
  python/instrumentation/openinference-instrumentation-langchain/tests/cassettes/test_instrumentor/test_tool_call_with_function.yaml
  python/instrumentation/openinference-instrumentation-langchain/tests/test_instrumentor.py
Labels: size:L

#1647 feat: Updates for new Agno verison
  python/instrumentation/openinference-instrumentation-agno/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-agno/pyproject.toml
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/__init__.py
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
Labels: size:L

#1611 feat(autogen-agentchat): auto instrumentation
  README.md
  python/instrumentation/openinference-instrumentation-autogen-agentchat/LICENSE
  python/instrumentation/openinference-instrumentation-autogen-agentchat/README.md
  python/instrumentation/openinference-instrumentation-autogen-agentchat/examples/assistant_agent_run.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-autogen-agentchat/examples/team_run.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/examples/team_run_stream.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/pyproject.toml
  python/instrumentation/openinference-instrumentation-autogen-agentchat/src/openinference/instrumentation/autogen_agentchat/__init__.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/src/openinference/instrumentation/autogen_agentchat/_wrappers.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/src/openinference/instrumentation/autogen_agentchat/version.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/test-requirements.txt
  python/instrumentation/openinference-instrumentation-autogen-agentchat/tests/__init__.py
  python/instrumentation/openinference-instrumentation-autogen-agentchat/tests/cassettes/TestAssistantAgent.test_agent_run.yaml
  python/instrumentation/openinference-instrumentation-autogen-agentchat/tests/cassettes/TestTeam.test_team_run.yaml
  python/instrumentation/openinference-instrumentation-autogen-agentchat/tests/test_instrumentor.py
  python/tox.ini
  release-please-config.json
Labels: size:XXL

#1662 docs: add documentation about prompt semantic conventions
  spec/semantic_conventions.md
Labels: size:L

#1663 feat(portkey): Add support for propmt template calls
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/__init__.py
  python/instrumentation/openinference-instrumentation-portkey/src/openinference/instrumentation/portkey/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-portkey/tests/cassettes/test_prompt_template.yaml
  python/instrumentation/openinference-instrumentation-portkey/tests/test_instrumentor.py
Labels: size:L

#1656 feat(bedrock): Multi Agent Support, capturing time metrics from metadata
  python/instrumentation/openinference-instrumentation-bedrock/DEVELOPER.md
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_agent.py
  python/instrumentation/openinference-instrumentation-bedrock/examples/bedrock_converse.py
  python/instrumentation/openinference-instrumentation-bedrock/pyproject.toml
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_attribute_extractor.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_response_accumulator.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/_trace_collector.py
  python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/utils/json_utils.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_agent_call_without_traces.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_knowledge_base_results.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_multi_agent_collaborator.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_post_processing_trace.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_preprocessing_trace.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_tool_calls_with_input_params.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/cassettes/test_tool_calls_without_input_params.yaml
  python/instrumentation/openinference-instrumentation-bedrock/tests/openinference/instrumentation/bedrock/test_invoke_agent_instrumentor.py
  python/instrumentation/openinference-instrumentation-bedrock/tests/test_trace_collector.py
Labels: size:XXL

#1598 feat: Mastra instrumentation
  .github/workflows/typescript-CI.yaml
  js/.changeset/fifty-shirts-design.md
  js/.changeset/many-needles-create.md
  js/.prettierignore
  js/packages/openinference-mastra/CHANGELOG.md
  js/packages/openinference-mastra/README.md
  js/packages/openinference-mastra/docs/mastra-weather-agent-spans.png
  js/packages/openinference-mastra/docs/mastra-weather-agent.png
  js/packages/openinference-mastra/package.json
  js/packages/openinference-mastra/src/OpenInferenceTraceExporter.ts
  js/packages/openinference-mastra/src/attributes.ts
  js/packages/openinference-mastra/src/debug.ts
  js/packages/openinference-mastra/src/index.ts
  js/packages/openinference-mastra/src/types.ts
  js/packages/openinference-mastra/src/utils.ts
  js/packages/openinference-mastra/test/OpenInferenceTraceExporter.test.ts
  js/packages/openinference-mastra/test/__fixtures__/weatherAgentSpans.json
  js/packages/openinference-mastra/test/__snapshots__/OpenInferenceTraceExporter.test.ts.export.json
  js/packages/openinference-mastra/tsconfig.esm.json
  js/packages/openinference-mastra/tsconfig.json
  js/packages/openinference-mastra/vitest.config.ts
  js/packages/openinference-vercel/package.json
  js/packages/openinference-vercel/src/utils.ts
  js/packages/openinference-vercel/test/OpenInferenceSpanProcessor.test.ts
  js/pnpm-lock.yaml
Labels: size:XXL

#1639 feat: pydanticai instrumentation
  README.md
  python/instrumentation/openinference-instrumentation-pydantic-ai/CHANGELOG.md
  python/instrumentation/openinference-instrumentation-pydantic-ai/LICENSE
  python/instrumentation/openinference-instrumentation-pydantic-ai/README.md
  python/instrumentation/openinference-instrumentation-pydantic-ai/examples/support_agent_with_tool.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/pyproject.toml
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/__init__.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/package.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/py.typed
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/semantic_conventions.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/span_processor.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/utils.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/version.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydanticai/cassettes/TestPydanticAIInstrumentation.test_pydantic_ai_instrumentation.yaml
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydanticai/conftest.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydanticai/test_instrumentor.py
  python/openinference-instrumentation/src/openinference/instrumentation/.gitignore
  python/tox.ini
  release-please-config.json
Labels: size:XXL

#1669 ci: Update .release-please-manifest.json for pydantic
  .release-please-manifest.json
Labels: size:XS

#1670 chore: update readme, add pydantic ai requirements
  README.md
  python/instrumentation/openinference-instrumentation-pydantic-ai/examples/requirements.txt
Labels: size:XS

#1682 fix(crewai): crewai default empty tasks
  python/instrumentation/openinference-instrumentation-crewai/pyproject.toml
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session.yaml
  python/instrumentation/openinference-instrumentation-crewai/tests/openinference/instrumentation/crewai/fixtures/crew_session_context_attributes.yaml
Labels: size:XXL

#1606 feat(instrumentation): add helpers for remaining semantic conventions
  python/openinference-instrumentation/examples/manual_llm_spans.ipynb
  python/openinference-instrumentation/examples/tracer.ipynb
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/_attributes.py
  python/openinference-instrumentation/src/openinference/instrumentation/_types.py
  python/openinference-instrumentation/tests/test_manual_instrumentation.py
Labels: size:L

#1700 feat(langchain-js): capture tool json schemas from LLM invocation parameters for llm calls with bound tools
  js/.changeset/smart-vans-refuse.md
  js/packages/openinference-instrumentation-langchain/examples/tool_calling.ts
  js/packages/openinference-instrumentation-langchain/src/types.ts
  js/packages/openinference-instrumentation-langchain/src/utils.ts
  js/packages/openinference-instrumentation-langchain/test/langchainV3.test.ts
Labels: size:M

#1697 fix(smolagents): include reasoning content
  python/instrumentation/openinference-instrumentation-smolagents/examples/env.example
  python/instrumentation/openinference-instrumentation-smolagents/examples/reasoning_content.py
  python/instrumentation/openinference-instrumentation-smolagents/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-smolagents/pyproject.toml
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/cassettes/test_instrumentor/TestModels.test_litellm_reasoning_model_has_expected_attributes.yaml
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:L

#1704 chore: Add mastra example app
  js/.changeset/fluffy-trees-add.md
  js/examples/mastra-openapi-phoenix-agent/.cursor/mcp.json
  js/examples/mastra-openapi-phoenix-agent/.gitignore
  js/examples/mastra-openapi-phoenix-agent/.nvmrc
  js/examples/mastra-openapi-phoenix-agent/README.md
  js/examples/mastra-openapi-phoenix-agent/package.json
  js/examples/mastra-openapi-phoenix-agent/src/mastra/agents/index.ts
  js/examples/mastra-openapi-phoenix-agent/src/mastra/env.ts
  js/examples/mastra-openapi-phoenix-agent/src/mastra/index.ts
  js/examples/mastra-openapi-phoenix-agent/src/mastra/storage.ts
  js/examples/mastra-openapi-phoenix-agent/tsconfig.json
  js/packages/openinference-mastra/package.json
  js/pnpm-lock.yaml
Labels: size:L

#1718 fix(dspy): upstream max token default value change
  python/instrumentation/openinference-instrumentation-dspy/tests/openinference/instrumentation/dspy/test_instrumentor.py
Labels: size:S

#1722 fix(litellm): display tool_calls from model output
  python/instrumentation/openinference-instrumentation-litellm/examples/litellm.py
  python/instrumentation/openinference-instrumentation-litellm/examples/litellm_openai.py
  python/instrumentation/openinference-instrumentation-litellm/examples/litellm_tools.py
  python/instrumentation/openinference-instrumentation-litellm/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
Labels: size:L

#1736 fix: CI Failures For Haystack
  python/instrumentation/openinference-instrumentation-haystack/src/openinference/instrumentation/haystack/_wrappers.py
  python/instrumentation/openinference-instrumentation-haystack/tests/openinference/haystack/test_instrumentor.py
Labels: size:XS

#1737 fix: filter sensitive model params
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
Labels: size:S

#1735 fix(litellm): full JSON output
  python/instrumentation/openinference-instrumentation-litellm/src/openinference/instrumentation/litellm/__init__.py
  python/instrumentation/openinference-instrumentation-litellm/tests/test_instrumentor.py
Labels: size:S
