Repository Arize-ai/openinference, pull requests merged in 2025-09, with the labels that each got.

#2132 feat: Support Guardrail Trace in Bedrock Agent Runtime TS instrumentation
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/attributeExtractionUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/attributeUtils.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/constants.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/attributes/types.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/collector/agentTraceAggregator.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/spanCreator.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/src/types.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/integration.instrumentation.agent-traces.test.ts
  js/packages/openinference-instrumentation-bedrock-agent-runtime/test/recordings/bedrock-agent-with-traces-bedrockagentinstrumentation-trace-collector-integration-agent-at_369038077/recording.har
Labels: size:XXL

#2134 feat(instrumentation): add dangerously_using_project context manager
  python/openinference-instrumentation/pyproject.toml
  python/openinference-instrumentation/src/openinference/instrumentation/__init__.py
  python/openinference-instrumentation/src/openinference/instrumentation/_projects.py
  python/openinference-instrumentation/src/openinference/instrumentation/_tracers.py
  python/openinference-instrumentation/tests/test_projects.py
Labels: size:L

#2142 fix: fixing mcp ci test timeout error
  python/instrumentation/openinference-instrumentation-mcp/tests/mcpserver.py
  python/instrumentation/openinference-instrumentation-mcp/tests/test_instrumenter.py
  python/instrumentation/openinference-instrumentation-mcp/tests/whoami.py
Labels: size:M

#2136 fix(Langchain): map UsageMetadata object
  python/instrumentation/openinference-instrumentation-langchain/src/openinference/instrumentation/langchain/_tracer.py
Labels: size:M, lgtm

#2202 feat(crewai): enhance span naming to include crew, agent, and tool context
  python/instrumentation/openinference-instrumentation-crewai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-crewai/examples/research_writer_crew.py
  python/instrumentation/openinference-instrumentation-crewai/src/openinference/instrumentation/crewai/_wrappers.py
  python/instrumentation/openinference-instrumentation-crewai/tests/test_instrumentor.py
  python/tox.ini
Labels: size:L

#2171 fix(smolagents): Not Getting Step Spans From Latest Smolagents
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/__init__.py
  python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py
  python/instrumentation/openinference-instrumentation-smolagents/tests/openinference/instrumentation/smolagents/test_instrumentor.py
Labels: size:L

#2211 fix: Agno v2 fixes
  python/instrumentation/openinference-instrumentation-agno/src/openinference/instrumentation/agno/_wrappers.py
  python/instrumentation/openinference-instrumentation-agno/tests/openinference/instrumentation/agno/fixtures/agent_run.yaml
  python/instrumentation/openinference-instrumentation-agno/tests/openinference/instrumentation/agno/fixtures/team_coordinate_run.yaml
  python/instrumentation/openinference-instrumentation-agno/tests/test_instrumentor.py
Labels: size:L, lgtm

#2212 fix(instructor): JSON Serialization Error for max_retries in Span Attributes
  python/instrumentation/openinference-instrumentation-instructor/src/openinference/instrumentation/instructor/_wrappers.py
  python/instrumentation/openinference-instrumentation-instructor/tests/openinference/instrumentation/instructor/test_instrumentation.py
Labels: size:M, lgtm

#2210 feat(openai): align embedding instrumentation with pending spec
  README.md
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_utils.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:L, lgtm

#2227 feat: update beeai-framework
  python/instrumentation/openinference-instrumentation-beeai/examples/chat.py
  python/instrumentation/openinference-instrumentation-beeai/examples/react_agent.py
  python/instrumentation/openinference-instrumentation-beeai/examples/requirement_agent.py
  python/instrumentation/openinference-instrumentation-beeai/examples/requirements.txt
  python/instrumentation/openinference-instrumentation-beeai/examples/tool_calling_agent.py
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/chat.py
Labels: size:M, lgtm

#2237 fix: pydantic-ai use final user message as input value
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/semantic_conventions.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/cassettes/test_openai_agent_and_llm_spans_v1.yaml
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/cassettes/test_openai_agent_and_llm_spans_v2.yaml
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/test_instrumentor.py
Labels: size:L
