Repository Arize-ai/openinference, pull requests merged in 2025-10, with the labels that each got.

#2253 fix(openai): handle complex output types in responses API for openai 2 compat
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_attributes/_responses_api.py
Labels: size:XS

#2250 fix: pydantic-ai properly instrument tools and instructions
  python/instrumentation/openinference-instrumentation-pydantic-ai/src/openinference/instrumentation/pydantic_ai/semantic_conventions.py
  python/instrumentation/openinference-instrumentation-pydantic-ai/tests/openinference/instrumentation/pydantic_ai/test_instrumentor.py
Labels: size:L, lgtm

#2254 test(openai): add unit tests for complex output serialization
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/_attributes/_responses_api/test_response_input_param.py
Labels: size:M

#2260 fix(google-genai): fix wrong tool attribute when setting llm input_message attribute
  python/instrumentation/openinference-instrumentation-google-genai/src/openinference/instrumentation/google_genai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-google-genai/tests/cassettes/test_generate_content.yaml
  python/instrumentation/openinference-instrumentation-google-genai/tests/test_instrumentation.py
Labels: size:L, lgtm, instrumentation: google genai

#2255 fix(beeai): update for RequirementAgent move from experimental to stable
  python/instrumentation/openinference-instrumentation-beeai/pyproject.toml
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/__init__.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/agents/requirement_agent.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/locator.py
  python/instrumentation/openinference-instrumentation-beeai/src/openinference/instrumentation/beeai/processors/requirement.py
Labels: size:S, lgtm

#2242 feat(openai): standardize completions to indexed attribute format
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
  python/openinference-instrumentation/src/openinference/instrumentation/config.py
  python/openinference-instrumentation/tests/test_config.py
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
  python/openinference-semantic-conventions/tests/openinference/semconv/test_attributes.py
  spec/configuration.md
  spec/llm_spans.md
  spec/semantic_conventions.md
Labels: size:L

#2279 fix(openai): update lower bound on openinference-semantic-conventions
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_image_utils.py
Labels: size:XS, lgtm

#2281 fix(semconv): refactor semconv
  python/openinference-semantic-conventions/src/openinference/semconv/trace/__init__.py
Labels: size:XS, lgtm

#2213 fix(openai): handle string format for image_url in chat completions
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_request_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/src/openinference/instrumentation/openai/_response_attributes_extractor.py
  python/instrumentation/openinference-instrumentation-openai/tests/openinference/instrumentation/openai/test_instrumentor.py
Labels: size:M

#2261 feat: anthropic js instrumentation
  js/packages/openinference-instrumentation-anthropic/CHANGELOG.md
  js/packages/openinference-instrumentation-anthropic/README.md
  js/packages/openinference-instrumentation-anthropic/examples/basic-usage.ts
  js/packages/openinference-instrumentation-anthropic/examples/streaming.ts
  js/packages/openinference-instrumentation-anthropic/examples/tool-use.ts
  js/packages/openinference-instrumentation-anthropic/package.json
  js/packages/openinference-instrumentation-anthropic/src/index.ts
  js/packages/openinference-instrumentation-anthropic/src/instrumentation.ts
  js/packages/openinference-instrumentation-anthropic/test/instrumentation.test.ts
  js/packages/openinference-instrumentation-anthropic/tsconfig.esm.json
  js/packages/openinference-instrumentation-anthropic/tsconfig.esnext.json
  js/packages/openinference-instrumentation-anthropic/tsconfig.json
  js/packages/openinference-instrumentation-anthropic/vitest.config.ts
  js/pnpm-lock.yaml
Labels: size:XXL
